Citizen.CreateThread(function()
    AddTextEntry("Cast1", "El Castillo del Diablo")
    AddTextEntry("Melsuda", "The Melasuda")
    AddTextEntry("Gouv7", "IAA Restricted Area")
    AddTextEntry("Verdant", "Verdant Meadows Airfield")
    AddTextEntry("Bone1", "Bone County")
    AddTextEntry("BigEar", "The Big Ear Radio Observatory")
    AddTextEntry("Carson", "Fort Carson")
end)