TabletActivities = {
    {
        id = "badweed",
        name = "Point Weed de mauvaise qualité",
        description = "Point de deal discret ; marchandise peu fiable mais prix d’entrée bas pour les petits réseaux.",
        image = "img/activities/badweed.png",
        coords = vector3(-1262.177002, 4492.421387, 9.502777),
    },
    {
        id = "gofast",
        name = "GoFast",
        description = "Course à haut risque entre zones ; livraison express et très surveillée par les forces de l’ordre.",
        image = "img/activities/gofast.png",
        coords = vector3(1240.814819, -438.573578, 67.751053),
    },
    {
        -- Coords = le PNJ donneur d'ordre au port de Paleto
        -- (cfg_gofast_mer.npc.pos, cf. sunlife/config/cfg_gofast_mer.lua),
        -- et non le point de livraison : la tablette ne pose qu'un GPS vers
        -- le point de DEPART de l'activite, comme pour le GoFast terrestre.
        id = "gofastmer",
        name = "GoFast maritime",
        description = "Convoi par la mer depuis les docks de Paleto ; trajets longs et gardes-côtes à éviter sur toute la route.",
        image = "img/activities/gofastmer.png",
        coords = vector3(-264.944763, 6642.209961, 7.492140),
    },
    {
        id = "chasseurprimes",
        name = "Chasseur de primes",
        description = "Rendez-vous avec un intermédiaire qui propose des contrats contre rémunération.",
        image = "img/activities/chasseurprimes.png",
        coords = vector3(-1471.433228, -909.270020, 10.129066),
    },
    {
        id = "braquageatm",
        name = "Braquage d'ATM",
        description = "Zone où les distributeurs sont régulièrement visés ; matériel et timing sont essentiels.",
        image = "img/activities/braquageatm.png",
        coords = vector3(-254.268219, -692.229919, 33.610661),
    },
    {
        id = "braquagesupp",
        name = "Braquage de supérette",
        description = "Commerce de proximité vulnérable ; entrées et issues à étudifier avant d’agir.",
        image = "img/activities/braquagesupp.png",
        coords = vector3(-1223.271362, -906.569580, 12.326351),
    },
    {
        id = "braquagevetements",
        name = "Braquage de magasins de vêtements",
        description = "Boutique adaptée à un coup rapide ; alarmes et caméras souvent présentes.",
        image = "img/activities/braquagevetements.png",
        coords = vector3(-1193.843262, -769.137268, 17.319433),
    },
    {
        id = "braquagebanque",
        name = "Braquage de banque",
        description = "Cible lourde : sécurité renforcée, gros gain possible et riposte des autorités quasi garantie.",
        image = "img/activities/braquagebanque.png",
        coords = vector3(241.106812, 228.924713, 106.282173),
    },
    {
        id = "chassepeausinge",
        name = "Chasse à la peau de singe",
        description = "Activité illégale sur une zone isolée ; trafic très sensible aux patrouilles.",
        image = "img/activities/chassepeausinge.png",
        coords = vector3(4864.559570, -4622.278320, 15.244611),
    },
    {
        id = "pecheillegale",
        name = "Pêche illégale",
        description = "Spot de pêche hors cadre ; douanes et gardes-côtes peuvent intervenir sans préavis.",
        image = "img/activities/pecheillegale.png",
        coords = vector3(4738.885254, -4914.916992, 2.923647),
    },
    {
        id = "braquagemusee",
        name = "Braquage du musée",
        description = "Site culturel fortement sécurisé ; coordination et discrétion indispensables.",
        image = "img/activities/braquagemusee.png",
        coords = vector3(209.945297, -184.943985, 54.595619),
    },
    {
        id = "braquagefleeca",
        name = "Braquage de Fleeca",
        description = "Agence bancaire compacte ; temps de réaction des unités d’intervention à prévoir.",
        image = "img/activities/braquagefleeca.png",
        coords = vector3(312.295471, -279.229309, 54.164551),
    },
    {
        id = "braquageconteneurs",
        name = "Braquage de conteneurs",
        description = "Zone portuaire ou industrielle ; chargement et fuite à organiser rapidement.",
        image = "img/activities/braquageconteneurs.png",
        coords = vector3(-1249.863525, -1195.786133, 7.592831),
    },
    {
        id = "volsacs",
        name = "Arrachage de sacs à mains",
        description = "Terrain propice aux vols à la tire ; mobilité et déguisement restent des atouts.",
        image = "img/activities/volsacs.png",
        coords = vector3(859.373230, -2273.416992, 30.345812),
    },
    {
        id = "cambriolages",
        name = "Cambriolages",
        description = "Quartier avec résidences ciblées ; silence et repérage des habitudes pour limiter les risques.",
        image = "img/activities/cambriolages.png",
        coords = vector3(-1377.221924, -333.830719, 39.157612),
    },
    {
        id = "ventedrogues",
        name = "Vente de drogues",
        description = "Angle de deal connu ; concurrence entre crews et présence possible des services.",
        image = "img/activities/ventedrogues.png",
        coords = vector3(52.869114, -1541.937500, 29.292860),
    },
}
