cfg_drugTerrain = {
    ["allPoints"] = {
        {
            name = "Plage",
            pos = vector3(-1446.9, -1313.19, 3.84),
            dst = 200,
            sprite = 304,
        },
        {
            name = "Mirrors Marks",
            pos = vector3(1174.1, -577.4, 64.33),
            dst = 200,
            sprite = 304,
        },
        {
            name = "Vinewood",
            pos = vector3(279.1, 168.77, 104.48),
            dst = 150,
            sprite = 304,
        },
        {
            name = "Sandy shores",
            pos = vector3(1348.1, 3563.74, 34.0),
            dst = 150,
            sprite = 304,
        },
        {
            name = "Grapseed",
            pos = vector3(1678.51, 4798.83, 42.0),
            dst = 100,
            sprite = 304,
        },
        {
            name = "Paleto bays",
            pos = vector3(-140.61, 6323.61, 31.62),
            dst = 175,
            sprite = 304,
        },
        {
            name = "New empire way",
            pos = vector3(-944.92, -2571.03, 13.83),
            dst = 175,
            sprite = 304,
        },
        {
            name = "Studio cinéma",
            pos = vector3(-1040.28, -472.57, 36.8),
            dst = 75,
            sprite = 304,
        },
        {
            name = "Zone industrielle",
            pos = vector3(929.62, -2065.19, 30.39),
            dst = 500,
            sprite = 304,
        },
    },
    ["randomPhrases"] = {
        ["first"] = {
            "Wesh mon reuf t'as de la drogue pour moi ou quoi",
            "Oh ça vend de la peuf ou quoi le zin",
            "Vas-y j'ai un pote il s'appelle ritchie il a besoin d'un bail t'as ?",
            "Salut... T'as de la drogue stp ?",
            "J'ai besoin d'un gros pochtar là magne avant qu'on nous crame",
            "EH FRÈRE J'VEUX D'LA DROGUE LÀ",
            "Assure je suis en manque de fou là",
            "C'est pour un pote t'inquiète mais t'as de la drogue stp ?",
        },

        ["sayNo"] = {
            "Ah ouais nan c'est trop cher pour moi ciao",
            "Nique tes morts",
            "Oh ça y est frère baise ta mère aussi avec tes prix",
            "Gros j'achète de la drogue pas un appartement",
            "Allez tfou avec tes prix de luxe là",
            "Petit fils de pute jamais je reviens te voir toi",
            "Ah ouais des prix vraiment",
            "Ah laisse tomber, t'as cru que j'étais riche ou quoi ?",
            "T'es sérieux avec ça ? J'me barre frère",
            "Wesh c'est quoi ces prix là ?",
            "C'est mort, je prends pas à ce prix",
            "Oh c'est trop, laisse tomber",
            "T'as cru que j'avais des thunes ou quoi ?",
            "C'est mort, je reviens plus ici",
            "Oh non, c'est pas pour moi, c'est trop cher",
            "T'es un ouf toi avec ces tarifs !",
            "Vas-y lâche l'affaire, c'est trop",
            "Frère, t'as pris la grosse tête ou quoi ?",
            "Trop cher pour ce que c'est, c'est mort",
            "Laisse tomber tes trucs, c'est abusé",
            "Oh j'suis pas millionnaire, va voir ailleurs",
            "Non mais sérieux, t'abuses avec tes prix",
            "Ah nan, c'est trop pour moi, ciao",
            "Franchement, c'est hors de prix",
            "T'as cru j'étais qui avec ton prix ?",
            "T'as fumé quoi pour mettre ce prix ?",
            "C'est abusé là, c'est bon je passe",
            "Non mais t'es fou, personne achète à ce prix",
            "Ah laisse tomber frère, t'abuses",
            "Tu me prends pour qui avec tes prix là ?",
            "Trop cher pour ce que c'est, je passe",
            "C'est bon, j'vais ailleurs",
            "Oublie, je prends pas à ce prix là",
            "Eh sérieux, t'as craqué ou quoi ?",
            "Non mais laisse tomber, j'vais trouver ailleurs",
            "Wesh, c'est quoi ces tarifs de fou ?",
            "Ah bah nan, je prends pas ça moi",
            "T'abuses avec ton prix, c'est bon j'pars",
            "Je vais trouver mieux ailleurs, c'est sûr",
            "Franchement, tu me dégoûtes avec ça",
            "Nan, je prends pas ça, c'est trop",
            "Nan mais t'as cru que j'étais blindé ?",
            "C'est pas possible ce prix là, oublie",
            "T'as cru que c'était Noël ou quoi ?",
            "Je suis pas ton pigeon, je prends pas",
            "Vas-y, laisse tomber avec ton prix",
            "T'es fou, je prends pas à ce tarif là",
            "Ah c'est trop cher, c'est mort",
            "T'es un malade toi, je pars direct",
            "Non mais t'es sérieux là ?",
        },

        ["sayYes"] = {
            "Vas-y c'est bon envoie la dope",
            "Un peu cher mais nique sa mère j'ai besoin",
            "Ah putain pas cher wesh vas-y t'en as combien ?",
            "Oh t'es un bon putain j'étais en manque sa mère",
            "T'es le seul qui avait de la drogue là putain merci",
            "Toi t'es pas un enfant de pute t'es un bon",
            "OH FRÈRE MERCI ENFIN J'EN POUVAIS PLUS",
            "Vas-y donne tout, t'es un bon toi",
            "Ouais c'est cool, passe-moi ça",
            "Bien ouèj, balance la came",
            "Oh merci frère, je t'en dois une",
            "Toi t'es un vrai, passe-moi ça",
            "Nickel, c'est bon, envoie le truc",
            "Ah ouais, pas cher, vas-y je prends tout",
            "Vas-y donne tout, on fait affaire",
            "C'est bon je prends tout frère",
            "Oh merci, t'es un vrai, passe-moi ça",
            "Enfin un bon prix, merci frère",
            "C'est bon je prends, balance la came",
            "T'es un bon, je reviendrai sûr",
            "Oh t'es un bon, merci wesh",
            "Ouais vas-y c'est cool, j'te prends tout",
            "Enfin quelqu'un de raisonnable, merci",
            "Vas-y c'est parfait, donne tout",
            "Toi t'es un bon, je te prends tout",
            "Ah ouais c'est carré ça, passe-moi ça",
            "Bien ouèj, je prends, c'est propre",
            "Merci, c'est bon je prends tout",
            "Toi t'es un vrai, balance tout frère",
            "T'es le meilleur, passe-moi ça",
            "C'est carré, vas-y je prends",
            "Tu gères, donne-moi tout",
            "Ah ouais merci, c'est propre ça",
            "T'es un bon, je prends tout",
            "C'est bon je prends, t'es au top",
            "Enfin quelqu'un qui gère bien",
            "Oh merci frère, t'es un bon",
            "Vas-y balance tout frère",
            "C'est parfait, je prends tout",
            "Bien joué frère, t'as tout ce qu'il faut",
            "Ouais c'est bon, donne-moi tout",
            "Enfin quelqu'un qui a de la vraie came",
            "T'es un bon, j'achète tout",
            "Merci, enfin je peux avoir ce qu'il me faut",
            "C'est bon, passe-moi ça direct",
            "Merci, t'as géré frère",
            "Toi t'es un vrai, je prends tout",
            "C'est carré, t'as tout ce qu'il faut",
            "Ouais merci frère, t'es au top",
        },

        ["callPolice"] = {
            "J'appelle les flics fils de pute",
            "T'as cru que j'allais te laisser tranquille ? Flics direct !",
            "Tu vas voir, j'appelle la police maintenant",
            "Les flics vont te niquer, attends un peu",
            "Flics direct, tu vas le regretter",
            "J'appelle la police maintenant, enfoiré",
            "Les flics vont te tomber dessus, attends un peu",
            "Je les appelle maintenant, tu vas voir",
            "T'es foutu, j'appelle les flics",
            "La police arrive, c'est fini pour toi",
            "Tu m'as énervé, flics direct",
            "Les flics arrivent, prépare-toi",
            "Je les appelle maintenant, tu vas voir",
            "Tu vas voir ce que ça fait d'appeler les flics",
            "Je te laisse pas tranquille, flics direct",
            "T'es mort, j'appelle les flics",
            "Je vais tout balancer aux flics",
            "Attends un peu, j'appelle les flics",
            "T'es foutu, la police arrive",
            "Je vais balancer tout aux flics",
            "Tu vas voir, flics direct",
            "C'est fini pour toi, les flics arrivent",
            "Tu vas le regretter, j'appelle la police",
            "Attends un peu, les flics arrivent",
            "C'est mort pour toi, les flics arrivent",
            "Tu vas voir ce que ça fait, les flics arrivent",
            "C'est fini pour toi, j'appelle la police",
            "Tu vas voir, les flics arrivent",
            "J'appelle les flics maintenant, enfoiré",
            "T'es foutu, la police arrive",
            "Tu vas le regretter, j'appelle les flics",
            "Les flics vont te tomber dessus",
            "Je balance tout aux flics",
            "Je vais te faire arrêter par les flics",
            "La police arrive, t'es foutu",
            "Les flics vont te choper, attends un peu",
            "Tu vas voir, j'appelle les flics maintenant",
            "Je te laisse pas partir, j'appelle les flics",
            "T'es foutu, j'appelle la police",
            "Les flics arrivent, prépare-toi",
            "Je vais balancer tout aux flics",
            "Tu vas voir, j'appelle les flics",
            "C'est fini pour toi, les flics arrivent",
            "La police arrive, t'es mort",
            "Je vais les appeler maintenant, tu vas voir",
            "Les flics vont te tomber dessus",
            "Je te laisse pas tranquille, flics direct",
            "T'es mort, j'appelle les flics",
        },

        ["attack"] = {
            "T'as cru j'étais un client sale batard ? Viens ta mère !",
            "Viens là, fils de pute, t'as cru que j'étais un pigeon ?",
            "Viens, sale chien, tu vas voir",
            "Je vais t'apprendre à respecter les clients !",
            "T'as cru que j'allais acheter ton truc ? Viens te battre !",
            "Viens ici, sale batard, tu vas voir !",
            "Tu veux me faire quoi là ? Viens !",
            "Viens me battre, sale chien, t'as cru que j'allais payer ?",
            "T'as pas peur ? Viens te battre !",
            "Viens là que je te fasse comprendre !",
            "T'as cru que t'étais en sécurité ? Viens te battre !",
            "Viens ici, sale traître, je vais te niquer !",
            "T'as vu tes prix ? Viens te battre !",
            "Viens là, tu vas voir ce que ça fait d'arnaquer les gens !",
            "Tu vas regretter, sale batard, viens ici !",
            "T'as cru que j'allais payer pour ça ? Viens ici !",
            "Viens me voir, je vais te niquer !",
            "T'as pris pour un pigeon ? Viens ici !",
            "Viens là, je vais t'apprendre la vie !",
            "Tu vas voir, je vais te démonter !",
            "Viens ici, sale batard, t'as cru que c'était facile ?",
            "Je vais te niquer, viens te battre !",
            "Viens là, que je te défonce !",
            "T'as cru que c'était facile de m'arnaquer ? Viens !",
            "Tu vas voir, je vais te massacrer !",
            "Viens là, je vais te faire regretter !",
            "Tu m'as pris pour un con ? Viens te battre !",
            "Viens là, tu vas voir ce que c'est que de se faire arnaquer !",
            "Je vais te niquer, viens te battre !",
            "Viens ici, sale traître !",
            "T'as cru que t'étais malin ? Viens te battre !",
            "Viens là, je vais te casser la gueule !",
            "Viens ici, que je te montre qui c'est le boss !",
            "T'as vu tes prix ? Je vais te niquer !",
            "Viens là, je vais te faire comprendre !",
            "Tu vas regretter de m'avoir arnaqué !",
            "T'as cru que j'étais un pigeon ? Viens ici !",
            "Viens ici, que je te fasse payer !",
            "Tu vas voir ce que ça fait de se faire arnaquer !",
            "T'as cru que c'était facile de m'avoir ? Viens ici !",
            "Viens te battre, sale chien, tu vas voir !",
            "Viens là, je vais te démonter !",
            "Tu m'as pris pour un pigeon ? Viens ici !",
            "Je vais te faire regretter, viens ici !",
            "Viens là, je vais te massacrer !",
            "T'as cru que j'allais payer ? Viens ici !",
            "Viens là, je vais te démonter !",
            "Viens te battre, t'as cru que j'étais un con ?",
        },
    },
    ["allPeds"] = {
        "a_m_m_polynesian_01",
        "a_m_m_prolhost_01",
        "a_m_m_salton_01",
        "a_m_m_soucent_03",
        "a_m_m_stlat_02",
        "a_m_m_trampbeac_01",
        "a_m_y_beachvesp_02",
        "a_m_y_eastsa_01",
        "a_m_y_golfer_01",
        "a_m_y_hipster_03",
        "a_m_y_latino_01",
        "a_m_y_juggalo_01",
        "a_m_y_mexthug_01",
        "a_m_y_soucent_03",
        "a_m_y_vinewood_01",
        "a_m_y_soucent_04",
        "cs_marnie",
        "g_f_y_vagos_01",
        "s_f_m_sweatshop_01",
        "s_m_m_autoshop_01",
        "s_m_m_bouncer_01",
        "s_m_m_ccrew_01",
        "s_m_m_cntrybar_01",
        "s_m_m_hairdress_01",
        "s_m_m_lifeinvad_01",
        "s_m_m_movprem_01",
        "s_m_m_lsmetro_01",
        "s_m_m_postal_02",
        "s_m_m_trucker_01",
        "ig_dale",
        "ig_kerrymcintosh_02",
        "ig_lacey_jones_02",
        "ig_kerrymcintosh",
        "ig_roccopelosi",
        "ig_russiandrunk",
        "ig_siemonyetarian",
        "ig_tylerdix_02",
    },
    ["rentabilityTexts"] = {
        [1] = "~r~Basse",
        [2] = "~o~Moyenne",
        [3] = "~y~Élevée",
        [4] = "~y~Très élevée",
        [5] = "~y~Très élevée",
        [6] = "~y~Très élevée",
    },
    ["blipsColors"] = {
        [1] = 1,
        [2] = 47,
        [3] = 2,
        [4] = 2,
        [5] = 2,
        [6] = 2,
    }
}
