ShopNPCConfig = {
    {
        id = "ltd_sud",
        job = "ltdsud",

        checkCenter = vector3(-707.40, -914.36, 19.22),
        checkRadius = 35.0,

        pedModel = "mp_m_shopkeep_01",
        pedCoords = vector4(-706.0662, -914.6116, 18.2156, 85.9878),
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",

        shopItems = {
            {name = "Wrap",                          item = "wrap",                price = 2000},
            {name = "Sandwich Thon",                 item = "thonsand",            price = 50},
            {name = "Sandwich Poulet",               item = "poulsand",            price = 50},
            {name = "Sandwich Saumon",               item = "saumsand",            price = 50},
            {name = "Eau",                           item = "eau",                 price = 30},
            {name = "Chips",                         item = "chips",               price = 30},
            {name = "Cola",                          item = "coca",                price = 30},
            {name = "Barre de chocolat",             item = "chocolat",            price = 30},
            {name = "Glace",                         item = "glace",               price = 30},
            {name = "Donut",                         item = "donut",               price = 30},
            {name = "Nouilles",                      item = "nouilles",            price = 30},
            {name = "Canne à pêche",                 item = "canne",               price = 1000},
            {name = "Appât",                         item = "appat",               price = 100},
            {name = "Téléphone",                     item = "classic_phone",       price = 500},
            {name = "Radio",                         item = "radio",               price = 1000},
            {name = "Voiture téléguidée",            item = "rc",                  price = 8000},
            {name = "Rollers",                       item = "roller",              price = 1500},
            {name = "Gants",                         item = "gants",               price = 1500},
            {name = "Chaise verte",                  item = "chaiseverte",         price = 750},
            {name = "Chaise bleue",                  item = "chaisebleue",         price = 750},
            {name = "Tenue de plongée",              item = "plongee",             price = 2000},
            {name = "Jumelles",                      item = "jumelles",            price = 1000},
            {name = "Parachute",                     item = "parachute",           price = 2000},
            {name = "Feu d'artifice starburst",      item = "starburst",           price = 5000},
            {name = "Feu d'artifice shotburst",      item = "shotburst",           price = 5000},
            {name = "Feu d'artifice fountain",       item = "fountain",            price = 5000},
            {name = "Feu d'artifice trailburst",     item = "trailburst",          price = 5000},
            {name = "Coyote",                        item = "coyote",              price = 2000},
            {name = "Brouilleur",                    item = "brouilleur",          price = 5000},
            {name = "Drone",                         item = "drone",               price = 10000},
            {name = "Corde",                         item = "corde",               price = 200},
            {name = "BMX",                           item = "bmx",                 price = 1000},
            {name = "Skateboard",                    item = "skateboard",          price = 1500},
            {name = "Puff",                          item = "puff",                price = 500},
            {name = "Bidon d'essence",               item = "WEAPON_PETROLCAN",    price = 1000},
            {name = "Ciseau",                        item = "ciseaux",             price = 500},
            {name = "Cahier de notes",               item = "cahier",              price = 250},
            {name = "Ticket à gratter",              item = "scratch_ticket",      price = 25000},
            {name = "Bombe peinture commune",        item = "bombepeinture",       price = 250000},
            {name = "Bombe peinture rare",           item = "bombepeinturerare",   price = 700000},
            {name = "Jacuzzi",                       item = "jacuzzi",             price = 250000},
            {name = "Paquet de clopes",              item = "paquet_clopes",       price = 1500},
        },
    },
    {
        id = "ltd_nord",
        job = "ltdnord",

        checkCenter = vector3(-47.089149475098, -1758.4282226562, 29.421010971069),
        checkRadius = 35.0,

        pedModel = "mp_m_shopkeep_01",
        pedCoords = vector4(-47.089149475098, -1758.4282226562, 28.421010971069, 51.799713134766),
        scenario = "WORLD_HUMAN_STAND_IMPATIENT",

        shopItems = {
            {name = "Wrap",                          item = "wrap",                price = 2000},
            {name = "Sandwich Thon",                 item = "thonsand",            price = 50},
            {name = "Sandwich Poulet",               item = "poulsand",            price = 50},
            {name = "Sandwich Saumon",               item = "saumsand",            price = 50},
            {name = "Eau",                           item = "eau",                 price = 30},
            {name = "Chips",                         item = "chips",               price = 30},
            {name = "Cola",                          item = "coca",                price = 30},
            {name = "Barre de chocolat",             item = "chocolat",            price = 30},
            {name = "Glace",                         item = "glace",               price = 30},
            {name = "Donut",                         item = "donut",               price = 30},
            {name = "Nouilles",                      item = "nouilles",            price = 30},
            {name = "Canne à pêche",                 item = "canne",               price = 1000},
            {name = "Appât",                         item = "appat",               price = 100},
            {name = "Téléphone",                     item = "classic_phone",       price = 500},
            {name = "Radio",                         item = "radio",               price = 1000},
            {name = "Voiture téléguidée",            item = "rc",                  price = 8000},
            {name = "Rollers",                       item = "roller",              price = 1500},
            {name = "Gants",                         item = "gants",               price = 1500},
            {name = "Chaise verte",                  item = "chaiseverte",         price = 750},
            {name = "Chaise bleue",                  item = "chaisebleue",         price = 750},
            {name = "Tenue de plongée",              item = "plongee",             price = 2000},
            {name = "Jumelles",                      item = "jumelles",            price = 1000},
            {name = "Parachute",                     item = "parachute",           price = 2000},
            {name = "Feu d'artifice starburst",      item = "starburst",           price = 5000},
            {name = "Feu d'artifice shotburst",      item = "shotburst",           price = 5000},
            {name = "Feu d'artifice fountain",       item = "fountain",            price = 5000},
            {name = "Feu d'artifice trailburst",     item = "trailburst",          price = 5000},
            {name = "Coyote",                        item = "coyote",              price = 2000},
            {name = "Brouilleur",                    item = "brouilleur",          price = 5000},
            {name = "Drone",                         item = "drone",               price = 10000},
            {name = "Corde",                         item = "corde",               price = 200},
            {name = "BMX",                           item = "bmx",                 price = 1000},
            {name = "Skateboard",                    item = "skateboard",          price = 1500},
            {name = "Puff",                          item = "puff",                price = 500},
            {name = "Bidon d'essence",               item = "WEAPON_PETROLCAN",    price = 1000},
            {name = "Ciseau",                        item = "ciseaux",             price = 500},
            {name = "Cahier de notes",               item = "cahier",              price = 250},
            {name = "Ticket à gratter",              item = "scratch_ticket",      price = 25000},
            {name = "Bombe peinture commune",        item = "bombepeinture",       price = 250000},
            {name = "Bombe peinture rare",           item = "bombepeinturerare",   price = 700000},
            {name = "Jacuzzi",                       item = "jacuzzi",             price = 250000},
            {name = "Paquet de clopes",              item = "paquet_clopes",       price = 1500},
        },
    },
}
