AddTextEntry("WEAPON_L85_CHRISTMAS", "L85 CHRISTMAS")
AddTextEntry("WEAPON_NVRIFLE_PURPLE", "NV Rifle Purple Gang")
AddTextEntry("WEAPON_FAMAS_YELLOW", "FAMAS Yellow Gang")
AddTextEntry("WEAPON_AKPUV2", "AKPUV2 Green Gang")
AddTextEntry("WEAPON_M4A5V2", "M4A5V Cyan Gang")
AddTextEntry("WEAPON_FOOLV2_RED", "FOOLV2 Red Gang")
AddTextEntry("WEAPON_FOOLV2", "FOOLV2weight")
AddTextEntry("WEAPON_GALILARV2", "GALILARV2 Black Gang")
AddTextEntry("WEAPON_HK516V2", "HK516V2 Blue Gang")
AddTextEntry("WEAPON_HFSMGV2", "HFSMGV2 ICE Glowing")
AddTextEntry("WEAPON_GRU2", "GRU2 Glowing")
AddTextEntry("WEAPON_GRAUV2", "GRAUV2 Glowing")
AddTextEntry("WEAPON_GYSV2", "GYSV2 Glowing")
AddTextEntry("WEAPON_NEVAV2", "NEVAV2 (Glows at night)")
AddTextEntry("WEAPON_MODULAR_RIFLE", "Modular Rifle")
AddTextEntry("WEAPON_NVRIFLE", "NV Rifle")
AddTextEntry("WEAPON_M4_T_NEON", "M4 TACTICAL NEON")
AddTextEntry("WEAPON_M27S", "M27Sweight")
AddTextEntry("WEAPON_HKUSP", "HKUSPistolweight")
AddTextEntry("WEAPON_M270D", "M270Dweight")
AddTextEntry("WEAPON_M4_HALLOWEEN", "M4 Halloween")
AddTextEntry("WEAPON_FAMAS", "Famasweight")
AddTextEntry("WEAPON_M4_A_W", "M4 Arctric White")
AddTextEntry("WEAPON_L85", "L85weight")
AddTextEntry("WEAPON_UMP", "UMPweight")
AddTextEntry("WEAPON_MP5", "MP5weight")
AddTextEntry("WEAPON_VECTOR", "Vectorweight")
AddTextEntry("WEAPON_BAS_P_RED", "BAS-P Red")
AddTextEntry("WEAPON_SCEVO", "CZ Scorpion EVO")
AddTextEntry("WEAPON_R90", "R90weight")
AddTextEntry("WEAPON_M133V3", "M133V3weight")
AddTextEntry("WEAPON_GAU_5A", "GAU 5A")
AddTextEntry("WEAPON_M82V2", "M82V2weight")
AddTextEntry("WEAPON_M47V2", "M47V2weight")
AddTextEntry("WEAPON_HOWAT20", "HOWA T20")
AddTextEntry("WEAPON_ISYV2", "ISYV2weight")
AddTextEntry("WEAPON_M4A1_MOD", "M4A1 MODs")
AddTextEntry("WEAPON_BERYL_762", "Beryl 762")
AddTextEntry("WEAPON_M4_TACTICAL_RED", "M4 TACTICAL RED")
AddTextEntry("WEAPON_AK47_NIGHTWISH", "AK-47 Nightswish")
AddTextEntry("WEAPON_XM7_6_8", "XM7_6_8 Black")
AddTextEntry("WEAPON_DESERT_EAGLE", "Desert Eagle")
AddTextEntry("WEAPON_SCAR-L", "SCAR-L Black")
AddTextEntry("WEAPON_AWP_ASIIMOV", "AWP Asiimov")
AddTextEntry("WEAPON_P250_ASIIMOV", "P250 Asiimov")
AddTextEntry("WEAPON_P20_ASIIMOV", "P20 Asiimov")
AddTextEntry("WEAPON_AK47_ASIIMOV", "AK-47 Asiimov")
AddTextEntry("WEAPON_M4ASIIMOV", "M4 Asiimov")
AddTextEntry("WEAPON_LMTM4R", "LMTM4R")
AddTextEntry("WEAPON_BULLPUP_SMG", "Bullpup SMG")