

fx_version 'adamant'
game 'gta5'

files {
	"audioconfig/*.dat151.rel",
	"audioconfig/*.dat54.rel",
	"audioconfig/*.dat10.rel",
	"sfx/**/*.awc"
}

data_file "AUDIO_SYNTHDATA" "audioconfig/lg125mnsrybently_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg125mnsrybently_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg125mnsrybently_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg125mnsrybently"
data_file 'AUDIO_GAMEDATA' 'audioconfig/apollosv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/apollosv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_apollosv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/c6v8sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/c6v8sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_c6v8sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/diablov12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/diablov12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_diablov12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f40v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f40v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f40v8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f50v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f50v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f50v12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ferrarif12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ferrarif12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ferrarif12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sestov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sestov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sestov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/urusv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/urusv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_urusv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/viperv10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/viperv10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_viperv10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/488sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/488sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_488sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/avesvv12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/avesvv12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_avesvv12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gtaspanov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gtaspanov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gtaspanov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/laferrarisound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/laferrarisound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_laferrarisound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mclarenv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mclarenv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mclarenv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/murciev12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/murciev12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_murciev12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/perfov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/perfov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_perfov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/veyronsound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/veyronsound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_veyronsound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/v6audiea839_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/v6audiea839_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v6audiea839'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg48lexlfa_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg48lexlfa_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg48lexlfa'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s85b50_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s85b50_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s85b50'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg187clkgtr_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg187clkgtr_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg187clkgtr'
data_file 'AUDIO_GAMEDATA' 'audioconfig/demonv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/demonv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_demonv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/kc115bmwe46st_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/kc115bmwe46st_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_kc115bmwe46st'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lg30meramgtr_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lg30meramgtr_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lg30meramgtr'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq2jzgterace_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq2jzgterace_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq2jzgterace'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r35sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r35sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r35sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ferrarif140fe_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ferrarif140fe_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ferrarif140fe'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg87skodar5rally_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg87skodar5rally_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg87skodar5rally_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg87skodar5rally"
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta103ninjah2r_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta103ninjah2r_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta103ninjah2r'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta122s58_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta122s58_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta122s58'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg62chironpursport_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg62chironpursport_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg62chironpursport_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg62chironpursport"
data_file 'AUDIO_GAMEDATA' 'audioconfig/superchargerdemonv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/superchargerdemonv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_superchargerdemonv8'
data_file "AUDIO_GAMEDATA" "audioconfig/w211_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/w211_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_w211"
data_file 'AUDIO_GAMEDATA' 'audioconfig/s55b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s55b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s55b30'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg123murcisp_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg123murcisp_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg123murcisp_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg123murcisp"
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta028viper_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta028viper_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta028viper'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqls7raceswap_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqls7raceswap_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqls7raceswap'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cummins5924v_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cummins5924v_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cummins5924v'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/n55b30t0_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n55b30t0_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n55b30t0'