Config                      = {}
Config.Locale               = 'fr'

Config.Accounts             = { 'bank', 'black_money', 'jetons' }
Config.AccountLabels        = { bank = _U('bank'), black_money = _U('black_money'), jetons = _U('jetons') }

Config.EnableSocietyPayouts = false -- pay from the society account that the player is employed at? Requirement: esx_society
Config.EnableHud            = false -- enable the default hud? Display current job and accounts (black, bank & cash)
Config.MaxWeight            = 35.0   -- the max inventory weight without backpack

Config.PaycheckInterval     = 15 * 60000

Config.EnableDebug          = false

Continental = {
    Security = {},
    ItemIndex = {},
}

Continental.AutomaticGiveAtConnexion = false

Continental.WeaponList = {
    -- Melee
    ['WEAPON_BEANBAG'] = {nameItem = 'WEAPON_BEANBAG', ammoCount = 250},
    ['WEAPON_DAGGER'] = {nameItem = 'WEAPON_DAGGER', ammoCount = 250},
    ['WEAPON_BAT'] = {nameItem = 'WEAPON_BAT', ammoCount = 250},
    ['WEAPON_BOTTLE'] = {nameItem = 'WEAPON_BOTTLE', ammoCount = 250},
    ['WEAPON_CROWBAR'] = {nameItem = 'WEAPON_CROWBAR', ammoCount = 250},
    ['WEAPON_FLASHLIGHT'] = {nameItem = 'WEAPON_FLASHLIGHT', ammoCount = 250},
    ['WEAPON_GOLFCLUB'] = {nameItem = 'WEAPON_GOLFCLUB', ammoCount = 250},
    ['WEAPON_HAMMER'] = {nameItem = 'WEAPON_HAMMER', ammoCount = 250},
    ['WEAPON_HATCHET'] = {nameItem = 'WEAPON_HATCHET', ammoCount = 250},
    ['WEAPON_KNUCKLE'] = {nameItem = 'WEAPON_KNUCKLE', ammoCount = 250},
    ['WEAPON_KNIFE'] = {nameItem = 'WEAPON_KNIFE', ammoCount = 250},
    ['WEAPON_MACHETE'] = {nameItem = 'WEAPON_MACHETE', ammoCount = 250},
    ['WEAPON_SWITCHBLADE'] = {nameItem = 'WEAPON_SWITCHBLADE', ammoCount = 250},
    ['WEAPON_NIGHTSTICK'] = {nameItem = 'WEAPON_NIGHTSTICK', ammoCount = 250},
    ['WEAPON_WRENCH'] = {nameItem = 'WEAPON_WRENCH', ammoCount = 250},
    ['WEAPON_BATTLEAXE'] = {nameItem = 'WEAPON_BATTLEAXE', ammoCount = 250},
    ['WEAPON_POOLCUE'] = {nameItem = 'WEAPON_POOLCUE', ammoCount = 250},
    ['WEAPON_STONE_HATCHET'] = {nameItem = 'WEAPON_STONE_HATCHET', ammoCount = 250},
    ['WEAPON_CANDYCANE'] = {nameItem = 'WEAPON_CANDYCANE', ammoCount = 250},
    -- Handguns
    ['WEAPON_PISTOL'] = {nameItem = 'WEAPON_PISTOL', ammoCount = 250},
    ['WEAPON_PISTOL_MK2'] = {nameItem = 'WEAPON_PISTOL_MK2', ammoCount = 250},
    ['WEAPON_COMBATPISTOL'] = {nameItem = 'WEAPON_COMBATPISTOL', ammoCount = 250},
    ['WEAPON_APPISTOL'] = {nameItem = 'WEAPON_APPISTOL', ammoCount = 250},
    ['WEAPON_STUNGUN'] = {nameItem = 'WEAPON_STUNGUN', ammoCount = 250},
    ['WEAPON_PISTOL50'] = {nameItem = 'WEAPON_PISTOL50', ammoCount = 250},
    ['WEAPON_SNSPISTOL'] = {nameItem = 'WEAPON_SNSPISTOL', ammoCount = 250},
    ['WEAPON_SNSPISTOL_MK2'] = {nameItem = 'WEAPON_SNSPISTOL_MK2', ammoCount = 250},
    ['WEAPON_HEAVYPISTOL'] = {nameItem = 'WEAPON_HEAVYPISTOL', ammoCount = 250},
    ['WEAPON_VINTAGEPISTOL'] = {nameItem = 'WEAPON_VINTAGEPISTOL', ammoCount = 250},
    ['WEAPON_FLAREGUN'] = {nameItem = 'WEAPON_FLAREGUN', ammoCount = 250},
    ['WEAPON_MARKSMANPISTOL'] = {nameItem = 'WEAPON_MARKSMANPISTOL', ammoCount = 250},
    ['WEAPON_REVOLVER'] = {nameItem = 'WEAPON_REVOLVER', ammoCount = 250},
    ['WEAPON_REVOLVER_MK2'] = {nameItem = 'WEAPON_REVOLVER_MK2', ammoCount = 250},
    ['WEAPON_DOUBLEACTION'] = {nameItem = 'WEAPON_DOUBLEACTION', ammoCount = 250},
    ['WEAPON_RAYPISTOL'] = {nameItem = 'WEAPON_RAYPISTOL', ammoCount = 250},
    ['WEAPON_CERAMICPISTOL'] = {nameItem = 'WEAPON_CERAMICPISTOL', ammoCount = 250},
    ['WEAPON_NAVYREVOLVER'] = {nameItem = 'WEAPON_NAVYREVOLVER', ammoCount = 250},
    ['WEAPON_GADGETPISTOL'] = {nameItem = 'WEAPON_GADGETPISTOL', ammoCount = 250},
    ['WEAPON_STUNGUN_MP'] = {nameItem = 'WEAPON_STUNGUN_MP', ammoCount = 250},
    ['WEAPON_PISTOLXM3'] = {nameItem = 'WEAPON_PISTOLXM3', ammoCount = 250},
    -- Submachine Guns
    ['WEAPON_MICROSMG'] = {nameItem = 'WEAPON_MICROSMG', ammoCount = 250},
    ['WEAPON_SMG'] = {nameItem = 'WEAPON_SMG', ammoCount = 250},
    ['WEAPON_SMG_MK2'] = {nameItem = 'WEAPON_SMG_MK2', ammoCount = 250},
    ['WEAPON_ASSAULTSMG'] = {nameItem = 'WEAPON_ASSAULTSMG', ammoCount = 250},
    ['WEAPON_COMBATPDW'] = {nameItem = 'WEAPON_COMBATPDW', ammoCount = 250},
    ['WEAPON_MACHINEPISTOL'] = {nameItem = 'WEAPON_MACHINEPISTOL', ammoCount = 250},
    ['WEAPON_MINISMG'] = {nameItem = 'WEAPON_MINISMG', ammoCount = 250},
    ['WEAPON_RAYCARBINE'] = {nameItem = 'WEAPON_RAYCARBINE', ammoCount = 250},
    ['WEAPON_TECPISTOL'] = {nameItem = 'WEAPON_TECPISTOL', ammoCount = 250},
    -- Shotguns
    ['WEAPON_PUMPSHOTGUN'] = {nameItem = 'WEAPON_PUMPSHOTGUN', ammoCount = 250},
    ['WEAPON_PUMPSHOTGUN_MK2'] = {nameItem = 'WEAPON_PUMPSHOTGUN_MK2', ammoCount = 250},
    ['WEAPON_SAWNOFFSHOTGUN'] = {nameItem = 'WEAPON_SAWNOFFSHOTGUN', ammoCount = 250},
    ['WEAPON_ASSAULTSHOTGUN'] = {nameItem = 'WEAPON_ASSAULTSHOTGUN', ammoCount = 250},
    ['WEAPON_BULLPUPSHOTGUN'] = {nameItem = 'WEAPON_BULLPUPSHOTGUN', ammoCount = 250},
    ['WEAPON_MUSKET'] = {nameItem = 'WEAPON_MUSKET', ammoCount = 250},
    ['WEAPON_HEAVYSHOTGUN'] = {nameItem = 'WEAPON_HEAVYSHOTGUN', ammoCount = 250},
    ['WEAPON_DBSHOTGUN'] = {nameItem = 'WEAPON_DBSHOTGUN', ammoCount = 250},
    ['WEAPON_AUTOSHOTGUN'] = {nameItem = 'WEAPON_AUTOSHOTGUN', ammoCount = 250},
    ['WEAPON_COMBATSHOTGUN'] = {nameItem = 'WEAPON_COMBATSHOTGUN', ammoCount = 250},
    -- Assault Rifles
    ['WEAPON_ASSAULTRIFLE'] = {nameItem = 'WEAPON_ASSAULTRIFLE', ammoCount = 250},
    ['WEAPON_ASSAULTRIFLE_MK2'] = {nameItem = 'WEAPON_ASSAULTRIFLE_MK2', ammoCount = 250},
    ['WEAPON_CARBINERIFLE'] = {nameItem = 'WEAPON_CARBINERIFLE', ammoCount = 250},
    ['WEAPON_CARBINERIFLE_MK2'] = {nameItem = 'WEAPON_CARBINERIFLE_MK2', ammoCount = 250},
    ['WEAPON_ADVANCEDRIFLE'] = {nameItem = 'WEAPON_ADVANCEDRIFLE', ammoCount = 250},
    ['WEAPON_SPECIALCARBINE'] = {nameItem = 'WEAPON_SPECIALCARBINE', ammoCount = 250},
    ['WEAPON_SPECIALCARBINE_MK2'] = {nameItem = 'WEAPON_SPECIALCARBINE_MK2', ammoCount = 250},
    ['WEAPON_BULLPUPRIFLE'] = {nameItem = 'WEAPON_BULLPUPRIFLE', ammoCount = 250},
    ['WEAPON_BULLPUPRIFLE_MK2'] = {nameItem = 'WEAPON_BULLPUPRIFLE_MK2', ammoCount = 250},
    ['WEAPON_COMPACTRIFLE'] = {nameItem = 'WEAPON_COMPACTRIFLE', ammoCount = 250},
    ['WEAPON_MILITARYRIFLE'] = {nameItem = 'WEAPON_MILITARYRIFLE', ammoCount = 250},
    ['WEAPON_HEAVYRIFLE'] = {nameItem = 'WEAPON_HEAVYRIFLE', ammoCount = 250},
    ['WEAPON_TACTICALRIFLE'] = {nameItem = 'WEAPON_TACTICALRIFLE', ammoCount = 250},
    -- Light Machine Guns
    ['WEAPON_MG'] = {nameItem = 'WEAPON_MG', ammoCount = 250},
    ['WEAPON_COMBATMG'] = {nameItem = 'WEAPON_COMBATMG', ammoCount = 250},
    ['WEAPON_COMBATMG_MK2'] = {nameItem = 'WEAPON_COMBATMG_MK2', ammoCount = 250},
    ['WEAPON_GUSENBERG'] = {nameItem = 'WEAPON_GUSENBERG', ammoCount = 250},
    -- Sniper Rifles
    ['WEAPON_SNIPERRIFLE'] = {nameItem = 'WEAPON_SNIPERRIFLE', ammoCount = 250},
    ['WEAPON_HEAVYSNIPER'] = {nameItem = 'WEAPON_HEAVYSNIPER', ammoCount = 250},
    ['WEAPON_HEAVYSNIPER_MK2'] = {nameItem = 'WEAPON_HEAVYSNIPER_MK2', ammoCount = 250},
    ['WEAPON_MARKSMANRIFLE'] = {nameItem = 'WEAPON_MARKSMANRIFLE', ammoCount = 250},
    ['WEAPON_MARKSMANRIFLE_MK2'] = {nameItem = 'WEAPON_MARKSMANRIFLE_MK2', ammoCount = 250},
    ['WEAPON_PRECISIONRIFLE'] = {nameItem = 'WEAPON_PRECISIONRIFLE', ammoCount = 250},
    -- Heavy Weapons
    ['WEAPON_RPG'] = {nameItem = 'WEAPON_RPG', ammoCount = 250},
    ['WEAPON_GRENADELAUNCHER'] = {nameItem = 'WEAPON_GRENADELAUNCHER', ammoCount = 250},
    ['WEAPON_GRENADELAUNCHER_SMOKE'] = {nameItem = 'WEAPON_GRENADELAUNCHER_SMOKE', ammoCount = 250},
    ['WEAPON_MINIGUN'] = {nameItem = 'WEAPON_MINIGUN', ammoCount = 250},
    ['WEAPON_FIREWORK'] = {nameItem = 'WEAPON_FIREWORK', ammoCount = 250},
    ['WEAPON_RAILGUN'] = {nameItem = 'WEAPON_RAILGUN', ammoCount = 250},
    ['WEAPON_HOMINGLAUNCHER'] = {nameItem = 'WEAPON_HOMINGLAUNCHER', ammoCount = 250},
    ['WEAPON_COMPACTLAUNCHER'] = {nameItem = 'WEAPON_COMPACTLAUNCHER', ammoCount = 250},
    ['WEAPON_RAYMINIGUN'] = {nameItem = 'WEAPON_RAYMINIGUN', ammoCount = 250},
    ['WEAPON_EMPLAUNCHER'] = {nameItem = 'WEAPON_EMPLAUNCHER', ammoCount = 250},
    ['WEAPON_RAILGUNXM3'] = {nameItem = 'WEAPON_RAILGUNXM3', ammoCount = 250},
    -- Throwables
    ['WEAPON_GRENADE'] = {nameItem = 'WEAPON_GRENADE', ammoCount = 250},
    ['WEAPON_BZGAS'] = {nameItem = 'WEAPON_BZGAS', ammoCount = 250},
    ['WEAPON_MOLOTOV'] = {nameItem = 'WEAPON_MOLOTOV', ammoCount = 250},
    ['WEAPON_STICKYBOMB'] = {nameItem = 'WEAPON_STICKYBOMB', ammoCount = 250},
    ['WEAPON_PROXMINE'] = {nameItem = 'WEAPON_PROXMINE', ammoCount = 250},
    ['WEAPON_SNOWBALL'] = {nameItem = 'WEAPON_SNOWBALL', ammoCount = 250},
    ['WEAPON_PIPEBOMB'] = {nameItem = 'WEAPON_PIPEBOMB', ammoCount = 250},
    ['WEAPON_BALL'] = {nameItem = 'WEAPON_BALL', ammoCount = 250},
    ['WEAPON_SMOKEGRENADE'] = {nameItem = 'WEAPON_SMOKEGRENADE', ammoCount = 250},
    ['WEAPON_FLARE'] = {nameItem = 'WEAPON_FLARE', ammoCount = 250},
    ['WEAPON_ACIDPACKAGE'] = {nameItem = 'WEAPON_ACIDPACKAGE', ammoCount = 250},
    ['WEAPON_FIREEXTINGUISHER'] = {nameItem = 'WEAPON_FIREEXTINGUISHER', ammoCount = 250},
    ['WEAPON_HAZARDCAN'] = {nameItem = 'WEAPON_HAZARDCAN', ammoCount = 250},
    ['WEAPON_FERTILIZERCAN'] = {nameItem = 'WEAPON_FERTILIZERCAN', ammoCount = 250},
    -- Modded
    ['WEAPON_HK416B'] = {nameItem = 'WEAPON_HK416B', ammoCount = 250},
    ['WEAPON_G19'] = {nameItem = 'WEAPON_G19', ammoCount = 250},
    ['WEAPON_MK18B'] = {nameItem = 'WEAPON_MK18B', ammoCount = 250},
    ['WEAPON_MP5'] = {nameItem = 'WEAPON_MP5', ammoCount = 250},
    ['WEAPON_LESSLETHAL'] = {nameItem = 'WEAPON_LESSLETHAL', ammoCount = 250},
    ['WEAPON_BREAD'] = {nameItem = 'WEAPON_BREAD', ammoCount = 250},
    ['WEAPON_DILDOCMG'] = {nameItem = 'WEAPON_DILDOCMG', ammoCount = 250},
    ['WEAPON_FIREAXECMG'] = {nameItem = 'WEAPON_FIREAXECMG', ammoCount = 250},
    ['WEAPON_GUITARCMG'] = {nameItem = 'WEAPON_GUITARCMG', ammoCount = 250},
    ['WEAPON_MP7CMG'] = {nameItem = 'WEAPON_MP7CMG', ammoCount = 250},
    ['WEAPON_SHOVELCMG'] = {nameItem = 'WEAPON_SHOVELCMG', ammoCount = 250},
    ['WEAPON_UMP45CMG'] = {nameItem = 'WEAPON_UMP45CMG', ammoCount = 250},
    ['WEAPON_PEPPERSPRAY'] = {nameItem = 'WEAPON_PEPPERSPRAY', ammoCount = 250},
    ['WEAPON_CHAINSAW'] = {nameItem = 'WEAPON_CHAINSAW', ammoCount = 250},
    ['WEAPON_SLICE'] = {nameItem = 'WEAPON_SLICE', ammoCount = 250},
    ['WEAPON_DEMHAMMER'] = {nameItem = 'WEAPON_DEMHAMMER', ammoCount = 250},
    ['WEAPON_KARAMBIT'] = {nameItem = 'WEAPON_KARAMBIT', ammoCount = 250},
    ['WEAPON_CANDYKNIFE'] = {nameItem = 'WEAPON_CANDYKNIFE', ammoCount = 250},
    ['WEAPON_SPECTREAQ'] = {nameItem = 'WEAPON_SPECTREAQ', ammoCount = 250},
    ['WEAPON_SCAR17'] = {nameItem = 'WEAPON_SCAR17', ammoCount = 250},
    ['WEAPON_SLIMAQ'] = {nameItem = 'WEAPON_SLIMAQ', ammoCount = 250},
    ['WEAPON_BATAQ'] = {nameItem = 'WEAPON_BATAQ', ammoCount = 250},
    ['WEAPON_AQAK'] = {nameItem = 'WEAPON_AQAK', ammoCount = 250},
    ['WEAPON_REDL'] = {nameItem = 'WEAPON_REDL', ammoCount = 250},
    ['WEAPON_M4_STORMBORN'] = {nameItem = 'WEAPON_M4_STORMBORN', ammoCount = 250},
    ['WEAPON_REDLINE_FANG'] = {nameItem = 'WEAPON_REDLINE_FANG', ammoCount = 250},
    ['WEAPON_HKUSP'] = {nameItem = 'WEAPON_HKUSP', ammoCount = 250},
    ['WEAPON_SLR15'] = {nameItem = 'WEAPON_SLR15', ammoCount = 250},
    ['WEAPON_XM7_6_8'] = {nameItem = 'WEAPON_XM7_6_8', ammoCount = 250},
    ['WEAPON_FAMAS'] = {nameItem = 'WEAPON_FAMAS', ammoCount = 250},
    ['WEAPON_FAMASC'] = {nameItem = 'WEAPON_FAMASC', ammoCount = 250},
    ['WEAPON_DESERTNIKE'] = {nameItem = 'WEAPON_DESERTNIKE', ammoCount = 250},
    ['WEAPON_M4BEAST'] = {nameItem = 'WEAPON_M4BEAST', ammoCount = 250},
    ['WEAPON_TEC9MF'] = {nameItem = 'WEAPON_TEC9MF', ammoCount = 250},
    ['WEAPON_PEPPERSPRAY'] = {nameItem = 'WEAPON_PEPPERSPRAY', ammoCount = 250},
    ['WEAPON_ANTIDOTE'] = {nameItem = 'WEAPON_ANTIDOTE', ammoCount = 250},
    ['WEAPON_MILITARYRIFLE'] = {nameItem = 'WEAPON_MILITARYRIFLE', ammoCount = 250},
    ['WEAPON_DOUBLEACTION'] = {nameItem = 'WEAPON_DOUBLEACTION', ammoCount = 250},
    ['WEAPON_PUMPKIN'] = {nameItem = 'WEAPON_PUMPKIN', ammoCount = 250},
    ['WEAPON_357'] = {nameItem = 'WEAPON_357', ammoCount = 250},
    ['WEAPON_CANDYKNIFE'] = {nameItem = 'WEAPON_CANDYKNIFE', ammoCount = 250},
    ['WEAPON_DESERTSANTA'] = {nameItem = 'WEAPON_DESERTSANTA', ammoCount = 250},
    ['WEAPON_HATMAS'] = {nameItem = 'WEAPON_HATMAS', ammoCount = 250},
    ['WEAPON_SANTAS'] = {nameItem = 'WEAPON_SANTAS', ammoCount = 250},
    ['WEAPON_XMASRIFLE'] = {nameItem = 'WEAPON_XMASRIFLE', ammoCount = 250},
    ['WEAPON_PISTOLXMAS'] = {nameItem = 'WEAPON_PISTOLXMAS', ammoCount = 250},
    ['WEAPON_SNOWXMAS'] = {nameItem = 'WEAPON_SNOWXMAS', ammoCount = 250},
    ['WEAPON_CARROTKNIFE'] = {nameItem = 'WEAPON_CARROTKNIFE', ammoCount = 250},
    ['WEAPON_REVOLVERULTRA'] = {nameItem = 'WEAPON_REVOLVERULTRA', ammoCount = 250},
    ['WEAPON_SIG550'] = {nameItem = 'WEAPON_SIG550', ammoCount = 250},
    ['WEAPON_M4LOVER'] = {nameItem = 'WEAPON_M4LOVER', ammoCount = 250},
    ['WEAPON_PBLACKVAL'] = {nameItem = 'WEAPON_PBLACKVAL', ammoCount = 250},
    ['WEAPON_WOLFKNIFE'] = {nameItem = 'WEAPON_WOLFKNIFE', ammoCount = 250},
    ['WEAPON_WOLFVERN'] = {nameItem = 'WEAPON_WOLFVERN', ammoCount = 250},
    ['WEAPON_ASSAULTRIFLELS'] = {nameItem = 'WEAPON_ASSAULTRIFLELS', ammoCount = 250},
    ['WEAPON_AKCARROT'] = {nameItem = 'WEAPON_AKCARROT', ammoCount = 250},
    ['WEAPON_CARROTSMG'] = {nameItem = 'WEAPON_CARROTSMG', ammoCount = 250},
    ['WEAPON_CARROTSWORD'] = {nameItem = 'WEAPON_CARROTSWORD', ammoCount = 250},
    ['WEAPON_CARROTTEC'] = {nameItem = 'WEAPON_CARROTTEC', ammoCount = 250},
    ['WEAPON_REVOCARROT'] = {nameItem = 'WEAPON_REVOCARROT', ammoCount = 250},
    ['WEAPON_PATRIOTKNIFE'] = {nameItem = 'WEAPON_PATRIOTKNIFE', ammoCount = 250},
    ['WEAPON_PISTOLPATRIOT'] = {nameItem = 'WEAPON_PISTOLPATRIOT', ammoCount = 250},
    ['WEAPON_PATRIOT'] = {nameItem = 'WEAPON_PATRIOT', ammoCount = 250},
    ['WEAPON_PF940'] = {nameItem = 'WEAPON_PF940', ammoCount = 250},
    ['WEAPON_SIGSPEARXM7'] = {nameItem = 'WEAPON_SIGSPEARXM7', ammoCount = 250},
    ['WEAPON_SIGMXCVIRTUS'] = {nameItem = 'WEAPON_SIGMXCVIRTUS', ammoCount = 250},
    ['WEAPON_FRYINPAN'] = {nameItem = 'WEAPON_FRYINPAN', ammoCount = 250},
    ['WEAPON_HFAP'] = {nameItem = 'WEAPON_HFAP', ammoCount = 250},
    ['WEAPON_UMP45'] = {nameItem = 'WEAPON_UMP45', ammoCount = 250},
    ['WEAPON_GK47'] = {nameItem = 'WEAPON_GK47', ammoCount = 250},
    ['WEAPON_A15RC'] = {nameItem = 'WEAPON_A15RC', ammoCount = 250},
    ['WEAPON_AK47_NIGHTWISH'] = {nameItem = 'WEAPON_AK47_NIGHTWISH', ammoCount = 250},
    ['WEAPON_BAS_P_RED'] = {nameItem = 'WEAPON_BAS_P_RED', ammoCount = 250},
    ['WEAPON_CZ75'] = {nameItem = 'WEAPON_CZ75', ammoCount = 250},
    ['WEAPON_SFTANA'] = {nameItem = 'WEAPON_SFTANA', ammoCount = 250},
    ['WEAPON_M4_T_NEON'] = {nameItem = 'WEAPON_M4_T_NEON', ammoCount = 250},
    ['WEAPON_P20_ASIIMOV'] = {nameItem = 'WEAPON_P20_ASIIMOV', ammoCount = 250},
    ['WEAPON_M4ASIIMOV'] = {nameItem = 'WEAPON_M4ASIIMOV', ammoCount = 250},
    ['WEAPON_M4A1_SPIKESHINE'] = {nameItem = 'WEAPON_M4A1_SPIKESHINE', ammoCount = 250},
    ['WEAPON_MINISMG_SPIKESHINE'] = {nameItem = 'WEAPON_MINISMG_SPIKESHINE', ammoCount = 250},
    ['WEAPON_BRICK'] = {nameItem = 'WEAPON_BRICK', ammoCount = 250},
    ['WEAPON_BRICK2'] = {nameItem = 'WEAPON_BRICK2', ammoCount = 250},
    ['WEAPON_AK_SHORTSTOCK_CHR'] = {nameItem = 'WEAPON_AK_SHORTSTOCK_CHR', ammoCount = 250},
    ['WEAPON_COMBAT_PISTOL_CHROMIUM'] = {nameItem = 'WEAPON_COMBAT_PISTOL_CHROMIUM', ammoCount = 250},
    ['WEAPON_GROZA_CHROMIUM'] = {nameItem = 'WEAPON_GROZA_CHROMIUM', ammoCount = 250},
    ['WEAPON_MP7_CHROMIUM'] = {nameItem = 'WEAPON_MP7_CHROMIUM', ammoCount = 250},
    ['WEAPON_VIOLET_VENGANGE_CHR'] = {nameItem = 'WEAPON_VIOLET_VENGANGE_CHR', ammoCount = 250},
    ['WEAPON_BULLPUP_SMG'] = {nameItem = 'WEAPON_BULLPUP_SMG', ammoCount = 250},
    ['WEAPON_AK_47_RED_CHROMIUM'] = {nameItem = 'WEAPON_AK_47_RED_CHROMIUM', ammoCount = 250},
    ['WEAPON_SCARSC'] = {nameItem = 'WEAPON_SCARSC', ammoCount = 250},
    ['WEAPON_MACHINE_PISTOL_RED_CHR'] = {nameItem = 'WEAPON_MACHINE_PISTOL_RED_CHR', ammoCount = 250},
    ['WEAPON_COMBATHP'] = {nameItem = 'WEAPON_COMBATHP', ammoCount = 250},
    ['WEAPON_NVRIFLE_PURPLE'] = {nameItem = 'WEAPON_NVRIFLE_PURPLE', ammoCount = 250},
    ['WEAPON_MP9'] = {nameItem = 'WEAPON_MP9', ammoCount = 250},
    ['WEAPON_EXTENDEDSMG'] = {nameItem = 'WEAPON_EXTENDEDSMG', ammoCount = 250},
    ['WEAPON_GOLDSMG'] = {nameItem = 'WEAPON_GOLDSMG', ammoCount = 250},
    ['WEAPON_VECTOR'] = {nameItem = 'WEAPON_VECTOR', ammoCount = 250},
    ['WEAPON_M415'] = {nameItem = 'WEAPON_M415', ammoCount = 250},
    ['WEAPON_AXE'] = {nameItem = 'WEAPON_AXE', ammoCount = 250},
    ['WEAPON_BARBEDBAT'] = {nameItem = 'WEAPON_BARBEDBAT', ammoCount = 250},
    ['WEAPON_BATON'] = {nameItem = 'WEAPON_BATON', ammoCount = 250},
    ['WEAPON_BLACKKATANA'] = {nameItem = 'WEAPON_BLACKKATANA', ammoCount = 250},
    ['WEAPON_KATANA'] = {nameItem = 'WEAPON_KATANA', ammoCount = 250},
    ['WEAPON_BLUEZK'] = {nameItem = 'WEAPON_BLUEZK', ammoCount = 250},
    ['WEAPON_BROWNMACHETE'] = {nameItem = 'WEAPON_BROWNMACHETE', ammoCount = 250},
    ['WEAPON_BUTCHER'] = {nameItem = 'WEAPON_BUTCHER', ammoCount = 250},
    ['WEAPON_CHAIR'] = {nameItem = 'WEAPON_CHAIR', ammoCount = 250},
    ['WEAPON_CRUTCH'] = {nameItem = 'WEAPON_CRUTCH', ammoCount = 250},
    ['WEAPON_DILDO'] = {nameItem = 'WEAPON_DILDO', ammoCount = 250},
    ['WEAPON_EGUITAR'] = {nameItem = 'WEAPON_EGUITAR', ammoCount = 250},
    ['WEAPON_GUITAR'] = {nameItem = 'WEAPON_GUITAR', ammoCount = 250},
    ['WEAPON_HUNTERKNIFE'] = {nameItem = 'WEAPON_HUNTERKNIFE', ammoCount = 250},
    ['WEAPON_ICECLIMBER'] = {nameItem = 'WEAPON_ICECLIMBER', ammoCount = 250},
    ['WEAPON_KITCHENKNIFE'] = {nameItem = 'WEAPON_KITCHENKNIFE', ammoCount = 250},
    ['WEAPON_KUKRI'] = {nameItem = 'WEAPON_KUKRI', ammoCount = 250},
    ['WEAPON_LONGMACHETE'] = {nameItem = 'WEAPON_LONGMACHETE', ammoCount = 250},
    ['WEAPON_MACE'] = {nameItem = 'WEAPON_MACE', ammoCount = 250},
    ['WEAPON_PICKAXE'] = {nameItem = 'WEAPON_PICKAXE', ammoCount = 250},
    ['WEAPON_PINKZK'] = {nameItem = 'WEAPON_PINKZK', ammoCount = 250},
    ['WEAPON_PITCHFORK'] = {nameItem = 'WEAPON_PITCHFORK', ammoCount = 250},
    ['WEAPON_REDZK'] = {nameItem = 'WEAPON_REDZK', ammoCount = 250},
    ['WEAPON_SCIFISWORD'] = {nameItem = 'WEAPON_SCIFISWORD', ammoCount = 250},
    ['WEAPON_SCIMITAR'] = {nameItem = 'WEAPON_SCIMITAR', ammoCount = 250},
    ['WEAPON_SCREWDRIVER'] = {nameItem = 'WEAPON_SCREWDRIVER', ammoCount = 250},
    ['WEAPON_SCYTHE'] = {nameItem = 'WEAPON_SCYTHE', ammoCount = 250},
    ['WEAPON_SHOVEL'] = {nameItem = 'WEAPON_SHOVEL', ammoCount = 250},
    ['WEAPON_SLEDGEHAMMER'] = {nameItem = 'WEAPON_SLEDGEHAMMER', ammoCount = 250},
    ['WEAPON_SPIKEDKNUCKLES'] = {nameItem = 'WEAPON_SPIKEDKNUCKLES', ammoCount = 250},
    ['WEAPON_SPIKEYBAT'] = {nameItem = 'WEAPON_SPIKEYBAT', ammoCount = 250},
    ['WEAPON_STOPSIGN'] = {nameItem = 'WEAPON_STOPSIGN', ammoCount = 250},
    ['WEAPON_TACAXE'] = {nameItem = 'WEAPON_TACAXE', ammoCount = 250},
    ['WEAPON_TACCLEAVER'] = {nameItem = 'WEAPON_TACCLEAVER', ammoCount = 250},
    ['WEAPON_TACTICALHATCHET'] = {nameItem = 'WEAPON_TACTICALHATCHET', ammoCount = 250},
    ['WEAPON_THORSHAMMER'] = {nameItem = 'WEAPON_THORSHAMMER', ammoCount = 250},
    ['WEAPON_TWOHBATTLEAXE'] = {nameItem = 'WEAPON_TWOHBATTLEAXE', ammoCount = 250},
    ['WEAPON_WCLAWS'] = {nameItem = 'WEAPON_WCLAWS', ammoCount = 250},
    ['WEAPON_ZK'] = {nameItem = 'WEAPON_ZK', ammoCount = 250},
    ['WEAPON_M133V3'] = {nameItem = 'WEAPON_M133V3', ammoCount = 250},
    ['WEAPON_TAR21'] = {nameItem = 'WEAPON_TAR21', ammoCount = 250},
    ['WEAPON_KS1'] = {nameItem = 'WEAPON_KS1', ammoCount = 250},
    ['WEAPON_PKISS'] = {nameItem = 'WEAPON_PKISS', ammoCount = 250},
    ['WEAPON_BATCANDY'] = {nameItem = 'WEAPON_BATCANDY', ammoCount = 250},
    ['WEAPON_KNIFEVALEN'] = {nameItem = 'WEAPON_KNIFEVALEN', ammoCount = 250},
    ['WEAPON_CZ_SCORPION_EVO_CHR'] = {nameItem = 'WEAPON_CZ_SCORPION_EVO_CHR', ammoCount = 250},
    ['WEAPON_SS2_2'] = {nameItem = 'WEAPON_SS2_2', ammoCount = 250},
    ['WEAPON_VERESK'] = {nameItem = 'WEAPON_VERESK', ammoCount = 250},
    ['WEAPON_MLTM4R_CHR'] = {nameItem = 'WEAPON_MLTM4R_CHR', ammoCount = 250},
    ['WEAPON_SPS_21_SG_CHR'] = {nameItem = 'WEAPON_SPS_21_SG_CHR', ammoCount = 250},
    ['WEAPON_TR_88_CHR'] = {nameItem = 'WEAPON_TR_88_CHR', ammoCount = 250},
    ['WEAPON_M270D_CHR'] = {nameItem = 'WEAPON_M270D_CHR', ammoCount = 250},
    ['WEAPON_DMRSNIPER'] = {nameItem = 'WEAPON_DMRSNIPER', ammoCount = 250},
    ['WEAPON_GAU_5A_FEM'] = {nameItem = 'WEAPON_GAU_5A_FEM', ammoCount = 250},
    ['WEAPON_HOWA_T20_CHR'] = {nameItem = 'WEAPON_HOWA_T20_CHR', ammoCount = 250},
    ['WEAPON_COMBAT_SG_CHR'] = {nameItem = 'WEAPON_COMBAT_SG_CHR', ammoCount = 250},
    ['WEAPON_SPX_7_CHR'] = {nameItem = 'WEAPON_SPX_7_CHR', ammoCount = 250},
    ['WEAPON_SR_3M_CHR'] = {nameItem = 'WEAPON_SR_3M_CHR', ammoCount = 250},
    ['WEAPON_HK2002M_CHR'] = {nameItem = 'WEAPON_HK2002M_CHR', ammoCount = 250},
    ['WEAPON_SYS_PISTOL_CHR'] = {nameItem = 'WEAPON_SYS_PISTOL_CHR', ammoCount = 250},
    ['WEAPON_SHOTGUN_CHROMIUM'] = {nameItem = 'WEAPON_SHOTGUN_CHROMIUM', ammoCount = 250},
    ['WEAPON_HX_15_CHR'] = {nameItem = 'WEAPON_HX_15_CHR', ammoCount = 250},
    ['WEAPON_SB_SD_CHR'] = {nameItem = 'WEAPON_SB_SD_CHR', ammoCount = 250},
    ['WEAPON_BONECLUB'] = {nameItem = 'WEAPON_BONECLUB', ammoCount = 250},
    ['WEAPON_BUCKET'] = {nameItem = 'WEAPON_BUCKET', ammoCount = 250},
    ['WEAPON_COFFIN'] = {nameItem = 'WEAPON_COFFIN', ammoCount = 250},
    ['WEAPON_DEATHNOTE'] = {nameItem = 'WEAPON_DEATHNOTE', ammoCount = 250},
    ['WEAPON_HELLFIRESWORD'] = {nameItem = 'WEAPON_HELLFIRESWORD', ammoCount = 250},
    ['WEAPON_INFERNO'] = {nameItem = 'WEAPON_INFERNO', ammoCount = 250},
    ['WEAPON_PUMPKIN'] = {nameItem = 'WEAPON_PUMPKIN', ammoCount = 250},
    ['WEAPON_PUMPKINBAT'] = {nameItem = 'WEAPON_PUMPKINBAT', ammoCount = 250},
    ['WEAPON_ARM'] = {nameItem = 'WEAPON_ARM', ammoCount = 250},
    ['WEAPON_LEG'] = {nameItem = 'WEAPON_LEG', ammoCount = 250},
    ['WEAPON_STAKE'] = {nameItem = 'WEAPON_STAKE', ammoCount = 250},
    ['WEAPON_TRIPLEBLADEDSCYTHE'] = {nameItem = 'WEAPON_TRIPLEBLADEDSCYTHE', ammoCount = 250},
    ['WEAPON_VOODOO'] = {nameItem = 'WEAPON_VOODOO', ammoCount = 250},
    ['WEAPON_WITCHBROOM'] = {nameItem = 'WEAPON_WITCHBROOM', ammoCount = 250},
    ['WEAPON_SOULSCYTHE'] = {nameItem = 'WEAPON_SOULSCYTHE', ammoCount = 250},
    ['WEAPON_GRAVESTONE'] = {nameItem = 'WEAPON_GRAVESTONE', ammoCount = 250},
    ['WEAPON_DIRTYSYRINGE'] = {nameItem = 'WEAPON_DIRTYSYRINGE', ammoCount = 250},
    ['WEAPON_BIGSPOON'] = {nameItem = 'WEAPON_BIGSPOON', ammoCount = 250},
    ['WEAPON_JABSAW'] = {nameItem = 'WEAPON_JABSAW', ammoCount = 250},
    ['WEAPON_TELESCOPE'] = {nameItem = 'WEAPON_TELESCOPE', ammoCount = 250},
    ['WEAPON_MEATSKEWER'] = {nameItem = 'WEAPON_MEATSKEWER', ammoCount = 250},
    ['WEAPON_SWORDFISH'] = {nameItem = 'WEAPON_SWORDFISH', ammoCount = 250},
    ['WEAPON_LOBSTER'] = {nameItem = 'WEAPON_LOBSTER', ammoCount = 250},
    ['WEAPON_PLIERS'] = {nameItem = 'WEAPON_PLIERS', ammoCount = 250},
    ['WEAPON_HANDDRILL'] = {nameItem = 'WEAPON_HANDDRILL', ammoCount = 250},
    ['WEAPON_TWISTEDSPEAR'] = {nameItem = 'WEAPON_TWISTEDSPEAR', ammoCount = 250},
    ['WEAPON_SNAKEKNIFE'] = {nameItem = 'WEAPON_SNAKEKNIFE', ammoCount = 250},
    ['WEAPON_CRUTCHKNIFE'] = {nameItem = 'WEAPON_CRUTCHKNIFE', ammoCount = 250},
    ['WEAPON_SHARPARROW'] = {nameItem = 'WEAPON_SHARPARROW', ammoCount = 250},
    ['WEAPON_95SIGN'] = {nameItem = 'WEAPON_95SIGN', ammoCount = 250},
    ['WEAPON_ASSASINGUN'] = {nameItem = 'WEAPON_ASSASINGUN', ammoCount = 250},
    ['WEAPON_BAGUETTE'] = {nameItem = 'WEAPON_BAGUETTE', ammoCount = 250},
    ['WEAPON_BANANA'] = {nameItem = 'WEAPON_BANANA', ammoCount = 250},
    ['WEAPON_BIKE'] = {nameItem = 'WEAPON_BIKE', ammoCount = 250},
    ['WEAPON_BONE'] = {nameItem = 'WEAPON_BONE', ammoCount = 250},
    ['WEAPON_BONESWORD'] = {nameItem = 'WEAPON_BONESWORD', ammoCount = 250},
    ['WEAPON_BUTTPLUG'] = {nameItem = 'WEAPON_BUTTPLUG', ammoCount = 250},
    ['WEAPON_CACTUS'] = {nameItem = 'WEAPON_CACTUS', ammoCount = 250},
    ['WEAPON_CAMSHAFT'] = {nameItem = 'WEAPON_CAMSHAFT', ammoCount = 250},
    ['WEAPON_CARJACK'] = {nameItem = 'WEAPON_CARJACK', ammoCount = 250},
    ['WEAPON_CONE'] = {nameItem = 'WEAPON_CONE', ammoCount = 250},
    ['WEAPON_CROSSSPANNER'] = {nameItem = 'WEAPON_CROSSSPANNER', ammoCount = 250},
    ['WEAPON_CUCUMBER'] = {nameItem = 'WEAPON_CUCUMBER', ammoCount = 250},
    ['WEAPON_DISABLEDSIGN'] = {nameItem = 'WEAPON_DISABLEDSIGN', ammoCount = 250},
    ['WEAPON_ELDERSWAND'] = {nameItem = 'WEAPON_ELDERSWAND', ammoCount = 250},
    ['WEAPON_MFIREEXTINGUISHER'] = {nameItem = 'WEAPON_MFIREEXTINGUISHER', ammoCount = 250},
    ['WEAPON_FISHINGROD'] = {nameItem = 'WEAPON_FISHINGROD', ammoCount = 250},
    ['WEAPON_GASCYLINDER'] = {nameItem = 'WEAPON_GASCYLINDER', ammoCount = 250},
    ['WEAPON_HOCKEYFSTICK'] = {nameItem = 'WEAPON_HOCKEYFSTICK', ammoCount = 250},
    ['WEAPON_HORN'] = {nameItem = 'WEAPON_HORN', ammoCount = 250},
    ['WEAPON_JDBOTTLE'] = {nameItem = 'WEAPON_JDBOTTLE', ammoCount = 250},
    ['WEAPON_KEYBOARD'] = {nameItem = 'WEAPON_KEYBOARD', ammoCount = 250},
    ['WEAPON_KITCHENFORK'] = {nameItem = 'WEAPON_KITCHENFORK', ammoCount = 250},
    ['WEAPON_LACROSSESTICK'] = {nameItem = 'WEAPON_LACROSSESTICK', ammoCount = 250},
    ['WEAPON_LADDER'] = {nameItem = 'WEAPON_LADDER', ammoCount = 250},
    ['WEAPON_MAILBOX'] = {nameItem = 'WEAPON_MAILBOX', ammoCount = 250},
    ['WEAPON_MIC'] = {nameItem = 'WEAPON_MIC', ammoCount = 250},
    ['WEAPON_NOPARKINGSIGN'] = {nameItem = 'WEAPON_NOPARKINGSIGN', ammoCount = 250},
    ['WEAPON_PEN'] = {nameItem = 'WEAPON_PEN', ammoCount = 250},
    ['WEAPON_PENCIL'] = {nameItem = 'WEAPON_PENCIL', ammoCount = 250},
    ['WEAPON_PROSLEG'] = {nameItem = 'WEAPON_PROSLEG', ammoCount = 250},
    ['WEAPON_ROLLINGPIN'] = {nameItem = 'WEAPON_ROLLINGPIN', ammoCount = 250},
    ['WEAPON_RONABOTTLE'] = {nameItem = 'WEAPON_RONABOTTLE', ammoCount = 250},
    ['WEAPON_ROUTE66SIGN'] = {nameItem = 'WEAPON_ROUTE66SIGN', ammoCount = 250},
    ['WEAPON_SCOOTER'] = {nameItem = 'WEAPON_SCOOTER', ammoCount = 250},
    ['WEAPON_SHOCKABSORBER'] = {nameItem = 'WEAPON_SHOCKABSORBER', ammoCount = 250},
    ['WEAPON_SKULLBAT'] = {nameItem = 'WEAPON_SKULLBAT', ammoCount = 250},
    ['WEAPON_SPARTANSWORD'] = {nameItem = 'WEAPON_SPARTANSWORD', ammoCount = 250},
    ['WEAPON_SPATULA'] = {nameItem = 'WEAPON_SPATULA', ammoCount = 250},
    ['WEAPON_STEPLADDER'] = {nameItem = 'WEAPON_STEPLADDER', ammoCount = 250},
    ['WEAPON_STREETLIGHT'] = {nameItem = 'WEAPON_STREETLIGHT', ammoCount = 250},
    ['WEAPON_TOASTER'] = {nameItem = 'WEAPON_TOASTER', ammoCount = 250},
    ['WEAPON_VACUUM'] = {nameItem = 'WEAPON_VACUUM', ammoCount = 250},
    ['WEAPON_WRONGWAYSIGN'] = {nameItem = 'WEAPON_WRONGWAYSIGN', ammoCount = 250},
    ['WEAPON_YARI'] = {nameItem = 'WEAPON_YARI', ammoCount = 250},
    ['WEAPON_BLACKBELT'] = {nameItem = 'WEAPON_BLACKBELT', ammoCount = 250},
    ['WEAPON_BENTFORK'] = {nameItem = 'WEAPON_BENTFORK', ammoCount = 250},
    ['WEAPON_BLACKBACKPACK'] = {nameItem = 'WEAPON_BLACKBACKPACK', ammoCount = 250},
    ['WEAPON_BRCHICKEN'] = {nameItem = 'WEAPON_BRCHICKEN', ammoCount = 250},
    ['WEAPON_DOORBARS'] = {nameItem = 'WEAPON_DOORBARS', ammoCount = 250},
    ['WEAPON_EARBUDBLADE'] = {nameItem = 'WEAPON_EARBUDBLADE', ammoCount = 250},
    ['WEAPON_HONEYDIPPER'] = {nameItem = 'WEAPON_HONEYDIPPER', ammoCount = 250},
    ['WEAPON_KETTLE'] = {nameItem = 'WEAPON_KETTLE', ammoCount = 250},
    ['WEAPON_LEATHERBRIEFCASE'] = {nameItem = 'WEAPON_LEATHERBRIEFCASE', ammoCount = 250},
    ['WEAPON_MAKESHIFTKNIFE'] = {nameItem = 'WEAPON_MAKESHIFTKNIFE', ammoCount = 250},
    ['WEAPON_MEASURINGCUP'] = {nameItem = 'WEAPON_MEASURINGCUP', ammoCount = 250},
    ['WEAPON_MODDEDNIGHTSTICK'] = {nameItem = 'WEAPON_MODDEDNIGHTSTICK', ammoCount = 250},
    ['WEAPON_TRAYRACK'] = {nameItem = 'WEAPON_TRAYRACK', ammoCount = 250},
    ['WEAPON_POKER'] = {nameItem = 'WEAPON_POKER', ammoCount = 250},
    ['WEAPON_PRISONKEY'] = {nameItem = 'WEAPON_PRISONKEY', ammoCount = 250},
    ['WEAPON_PRISTOI'] = {nameItem = 'WEAPON_PRISTOI', ammoCount = 250},
    ['WEAPON_REDBACKPACK'] = {nameItem = 'WEAPON_REDBACKPACK', ammoCount = 250},
    ['WEAPON_RULER'] = {nameItem = 'WEAPON_RULER', ammoCount = 250},
    ['WEAPON_SHIV'] = {nameItem = 'WEAPON_SHIV', ammoCount = 250},
    ['WEAPON_SOLIDOOR'] = {nameItem = 'WEAPON_SOLIDOOR', ammoCount = 250},
    ['WEAPON_TEAPOT'] = {nameItem = 'WEAPON_TEAPOT', ammoCount = 250},
    ['WEAPON_VIOBACKPACK'] = {nameItem = 'WEAPON_VIOBACKPACK', ammoCount = 250},
    ['WEAPON_PEELER'] = {nameItem = 'WEAPON_PEELER', ammoCount = 250},
    ['WEAPON_G36'] = {nameItem = 'WEAPON_G36', ammoCount = 250},
    ['WEAPON_G3_2'] = {nameItem = 'WEAPON_G3_2', ammoCount = 250},
    ['WEAPON_L85_CHR'] = {nameItem = 'WEAPON_L85_CHR', ammoCount = 250},
    ['WEAPON_VX_SCORPION_CHR'] = {nameItem = 'WEAPON_VX_SCORPION_CHR', ammoCount = 250},
    ['WEAPON_R90_CHR'] = {nameItem = 'WEAPON_R90_CHR', ammoCount = 250},
    ['WEAPON_ASSAULTRIFLECUPID'] = {nameItem = 'WEAPON_ASSAULTRIFLECUPID', ammoCount = 250},
    ['WEAPON_ASSAULTRIFLE_MK2_DARKMATTER'] = {nameItem = 'WEAPON_ASSAULTRIFLE_MK2_DARKMATTER', ammoCount = 250},
    ['WEAPON_CARBINERIFLE_MK2_DARKMATTER'] = {nameItem = 'WEAPON_CARBINERIFLE_MK2_DARKMATTER', ammoCount = 250},
    ['WEAPON_SPECIALCARBINE_MK2_DARKMATTER'] = {nameItem = 'WEAPON_SPECIALCARBINE_MK2_DARKMATTER', ammoCount = 250},
    ['WEAPON_MICROSMG_DARKMATTER'] = {nameItem = 'WEAPON_MICROSMG_DARKMATTER', ammoCount = 250},
    ['WEAPON_REVOLVER_MK2_DARKMATTER'] = {nameItem = 'WEAPON_REVOLVER_MK2_DARKMATTER', ammoCount = 250},
    ['WEAPON_KNUCKLE_DARKMATTER'] = {nameItem = 'WEAPON_KNUCKLE_DARKMATTER', ammoCount = 250},
    ['WEAPON_HOSE'] = {nameItem = 'WEAPON_HOSE', ammoCount = 250},
    ['WEAPON_M249'] = {nameItem = 'WEAPON_M249', ammoCount = 250},
    ['WEAPON_MK14'] = {nameItem = 'WEAPON_MK14', ammoCount = 250},
    ['WEAPON_RRT14_GANG'] = {nameItem = 'WEAPON_RRT14_GANG', ammoCount = 250},
    ['WEAPON_P320_GANG'] = {nameItem = 'WEAPON_P320_GANG', ammoCount = 250},
}

Continental.ContribWeapons = {
    ['WEAPON_FRYINPAN'] = true,
    ['WEAPON_HFAP'] = true,
    ['WEAPON_UMP45'] = true,
    ['WEAPON_GK47'] = true,
    ['WEAPON_A15RC'] = true,
    ['WEAPON_AK47_NIGHTWISH'] = true,
    ['WEAPON_BAS_P_RED'] = true,
    ['WEAPON_CZ75'] = true,
    ['WEAPON_SFTANA'] = true,
    ['WEAPON_M4_T_NEON'] = true,
    ['WEAPON_M4LOVER'] = true,
    ['WEAPON_PBLACKVAL'] = true,
    ['WEAPON_WOLFKNIFE'] = true,
    ['WEAPON_WOLFVERN'] = true,
    ['WEAPON_ASSAULTRIFLELS'] = true,
	['WEAPON_BATAQ'] = true,
	['WEAPON_HEAVYSNIPER'] = true,
	['WEAPON_REVOLVER_MK2'] = true,
	['WEAPON_SPS_21_SG_CHR'] = true,
	['WEAPON_HUNTSMAN'] = true,
	['WEAPON_CERAMICPISTOL'] = true,
	['WEAPON_NAVYREVOLVER'] = true,
	['WEAPON_SPECTREAQ'] = true,
	['WEAPON_SLIMAQ'] = true,
    ['WEAPON_AQAK'] = true,
    ['WEAPON_M4BEAST'] = true,
    ['WEAPON_TEC9MF'] = true,
	['WEAPON_PATRIOTKNIFE'] = true,
    ['WEAPON_PISTOLPATRIOT'] = true,
    ['WEAPON_PATRIOT'] = true,
	['WEAPON_CASABLANCA'] = true,
	['WEAPON_SCAR17'] = true,
	['WEAPON_GADGETPISTOL'] = true,
	['WEAPON_STONE_HATCHET']  = true,
	['WEAPON_TRIDAGGERSILVER'] = true,
	['WEAPON_PREDATOR'] = true,
	['WEAPON_BLASTM4'] = true,
	['WEAPON_BLACKSNIPER'] = true,
	['WEAPON_BLASTAK'] = true,
	['WEAPON_GOLDM'] = true,
	['WEAPON_MILITARM4'] = true,
	['WEAPON_AKORUS'] = true,
	['WEAPON_REDL'] = true,
	['WEAPON_M4_STORMBORN'] = true,
	['WEAPON_REDLINE_FANG'] = true,
    ['WEAPON_FAMAS'] = true,
    ['WEAPON_FAMASC'] = true,
	['WEAPON_DESERTNIKE'] = true,
    ['WEAPON_DEMHAMMER'] = true,
    ['WEAPON_CHAINSAW'] = true,
    ['WEAPON_PUMPKIN'] = true,
    ['WEAPON_357'] = true,
    ['WEAPON_SLICE'] = true,
    ['WEAPON_CANDYKNIFE'] = true,
    ['WEAPON_DESERTSANTA'] = true,
    ['WEAPON_HATMAS'] = true,
    ['WEAPON_SANTAS'] = true,
    ['WEAPON_BREAD'] = true,
    ['WEAPON_XMASRIFLE'] = true,
    ['WEAPON_PISTOLXMAS'] = true,
    ['WEAPON_SNOWXMAS'] = true,
    ['WEAPON_CARROTKNIFE'] = true,
    ['WEAPON_REVOLVERULTRA'] = true,
    ['WEAPON_SIG550'] = true,
    ['WEAPON_AKCARROT'] = true,
    ['WEAPON_CARROTSMG'] = true,
    ['WEAPON_CARROTSWORD'] = true,
    ['WEAPON_CARROTTEC'] = true,
    ['WEAPON_PF940'] = true,
    ['WEAPON_SIGSPEARXM7'] = true,
    ['WEAPON_SIGMXCVIRTUS'] = true,
    ['WEAPON_REVOCARROT'] = true,
    ['WEAPON_P20_ASIIMOV'] = true,
    ['WEAPON_BRICK'] = true,
    ['WEAPON_BRICK2'] = true,
    ['WEAPON_M4ASIIMOV'] = true,
    ['WEAPON_M4A1_SPIKESHINE'] = true,
    ['WEAPON_MINISMG_SPIKESHINE'] = true,
    ['WEAPON_AK_SHORTSTOCK_CHR'] = true,
    ['WEAPON_COMBAT_PISTOL_CHROMIUM'] = true,
    ['WEAPON_GROZA_CHROMIUM'] = true,
    ['WEAPON_MP7_CHROMIUM'] = true,
    ['WEAPON_VIOLET_VENGANGE_CHR'] = true,
    ['WEAPON_BULLPUP_SMG'] = true,
    ['WEAPON_AK_47_RED_CHROMIUM'] = true,
    ['WEAPON_SCARSC'] = true,
    ['WEAPON_MACHINE_PISTOL_RED_CHR'] = true,
    ['WEAPON_COMBATHP'] = true,
    ['WEAPON_NVRIFLE_PURPLE'] = true,
    ['WEAPON_MP9'] = true,
    ['WEAPON_EXTENDEDSMG'] = true,
    ['WEAPON_GOLDSMG'] = true,
    ['WEAPON_VECTOR'] = true,
    ['WEAPON_M415'] = true,
    ['WEAPON_AXE'] = true,
    ['WEAPON_BARBEDBAT'] = true,
    ['WEAPON_BLACKKATANA'] = true,
    ['WEAPON_KATANA'] = true,
    ['WEAPON_BLUEZK'] = true,
    ['WEAPON_BROWNMACHETE'] = true,
    ['WEAPON_BUTCHER'] = true,
    ['WEAPON_CHAIR'] = true,
    ['WEAPON_CRUTCH'] = true,
    ['WEAPON_DILDO'] = true,
    ['WEAPON_EGUITAR'] = true,
    ['WEAPON_GUITAR'] = true,
    ['WEAPON_HUNTERKNIFE'] = true,
    ['WEAPON_ICECLIMBER'] = true,
    ['WEAPON_KITCHENKNIFE'] = true,
    ['WEAPON_KUKRI'] = true,
    ['WEAPON_LONGMACHETE'] = true,
    ['WEAPON_MACE'] = true,
    ['WEAPON_PICKAXE'] = true,
    ['WEAPON_PINKZK'] = true,
    ['WEAPON_PITCHFORK'] = true,
    ['WEAPON_REDZK'] = true,
    ['WEAPON_SCIFISWORD'] = true,
    ['WEAPON_SCIMITAR'] = true,
    ['WEAPON_SCYTHE'] = true,
    ['WEAPON_SHOVEL'] = true,
    ['WEAPON_SLEDGEHAMMER'] = true,
    ['WEAPON_SPIKEDKNUCKLES'] = true,
    ['WEAPON_SPIKEYBAT'] = true,
    ['WEAPON_STOPSIGN'] = true,
    ['WEAPON_TACAXE'] = true,
    ['WEAPON_TACCLEAVER'] = true,
    ['WEAPON_TACTICALHATCHET'] = true,
    ['WEAPON_THORSHAMMER'] = true,
    ['WEAPON_TWOHBATTLEAXE'] = true,
    ['WEAPON_WCLAWS'] = true,
    ['WEAPON_ZK'] = true,
    ['WEAPON_M133V3'] = true,
    ['WEAPON_TAR21'] = true,
    ['WEAPON_KS1'] = true,
    ['WEAPON_HKUSP'] = true,
    ['WEAPON_SLR15'] = true,
    ['WEAPON_XM7_6_8'] = true,
    ['WEAPON_PKISS'] = true,
    ['WEAPON_BATCANDY'] = true,
    ['WEAPON_KNIFEVALEN'] = true,
    ['WEAPON_DILDOCMG'] = true,
    ['WEAPON_CZ_SCORPION_EVO_CHR'] = true,
    ['WEAPON_SS2_2'] = true,
    ['WEAPON_VERESK'] = true,
    ['WEAPON_MLTM4R_CHR'] = true,
    ['WEAPON_TR_88_CHR'] = true,
    ['WEAPON_M270D_CHR'] = true,
    ['WEAPON_DMRSNIPER'] = true,
    ['WEAPON_GAU_5A_FEM'] = true,
    ['WEAPON_HOWA_T20_CHR'] = true,
    ['WEAPON_COMBAT_SG_CHR'] = true,
    ['WEAPON_SPX_7_CHR'] = true,
    ['WEAPON_SR_3M_CHR'] = true,
    ['WEAPON_HK2002M_CHR'] = true,
    ['WEAPON_SYS_PISTOL_CHR'] = true,
    ['WEAPON_SHOTGUN_CHROMIUM'] = true,
    ['WEAPON_HX_15_CHR'] = true,
    ['WEAPON_BONECLUB'] = true,
    ['WEAPON_BUCKET'] = true,
    ['WEAPON_COFFIN'] = true,
    ['WEAPON_DEATHNOTE'] = true,
    ['WEAPON_HELLFIRESWORD'] = true,
    ['WEAPON_INFERNO'] = true,
    ['WEAPON_PUMPKIN'] = true,
    ['WEAPON_PUMPKINBAT'] = true,
    ['WEAPON_ARM'] = true,
    ['WEAPON_LEG'] = true,
    ['WEAPON_STAKE'] = true,
    ['WEAPON_TRIPLEBLADEDSCYTHE'] = true,
    ['WEAPON_VOODOO'] = true,
    ['WEAPON_WITCHBROOM'] = true,
    ['WEAPON_SOULSCYTHE'] = true,
    ['WEAPON_GRAVESTONE'] = true,
    ['WEAPON_DIRTYSYRINGE'] = true,
    ['WEAPON_BIGSPOON'] = true,
    ['WEAPON_JABSAW'] = true,
    ['WEAPON_TELESCOPE'] = true,
    ['WEAPON_MEATSKEWER'] = true,
    ['WEAPON_SWORDFISH'] = true,
    ['WEAPON_LOBSTER'] = true,
    ['WEAPON_PLIERS'] = true,
    ['WEAPON_HANDDRILL'] = true,
    ['WEAPON_TWISTEDSPEAR'] = true,
    ['WEAPON_SNAKEKNIFE'] = true,
    ['WEAPON_CRUTCHKNIFE'] = true,
    ['WEAPON_SHARPARROW'] = true,
    ['WEAPON_95SIGN'] = true,
    ['WEAPON_ASSASINGUN'] = true,
    ['WEAPON_BAGUETTE'] = true,
    ['WEAPON_BANANA'] = true,
    ['WEAPON_BIKE'] = true,
    ['WEAPON_BONE'] = true,
    ['WEAPON_BONESWORD'] = true,
    ['WEAPON_BUTTPLUG'] = true,
    ['WEAPON_CACTUS'] = true,
    ['WEAPON_CAMSHAFT'] = true,
    ['WEAPON_CARJACK'] = true,
    ['WEAPON_CONE'] = true,
    ['WEAPON_CROSSSPANNER'] = true,
    ['WEAPON_CUCUMBER'] = true,
    ['WEAPON_DISABLEDSIGN'] = true,
    ['WEAPON_ELDERSWAND'] = true,
    ['WEAPON_MFIREEXTINGUISHER'] = true,
    ['WEAPON_FISHINGROD'] = true,
    ['WEAPON_GASCYLINDER'] = true,
    ['WEAPON_HOCKEYFSTICK'] = true,
    ['WEAPON_HORN'] = true,
    ['WEAPON_JDBOTTLE'] = true,
    ['WEAPON_KEYBOARD'] = true,
    ['WEAPON_KITCHENFORK'] = true,
    ['WEAPON_LACROSSESTICK'] = true,
    ['WEAPON_LADDER'] = true,
    ['WEAPON_MAILBOX'] = true,
    ['WEAPON_MIC'] = true,
    ['WEAPON_NOPARKINGSIGN'] = true,
    ['WEAPON_PEN'] = true,
    ['WEAPON_PENCIL'] = true,
    ['WEAPON_PROSLEG'] = true,
    ['WEAPON_ROLLINGPIN'] = true,
    ['WEAPON_RONABOTTLE'] = true,
    ['WEAPON_ROUTE66SIGN'] = true,
    ['WEAPON_SCOOTER'] = true,
    ['WEAPON_SHOCKABSORBER'] = true,
    ['WEAPON_SKULLBAT'] = true,
    ['WEAPON_SPARTANSWORD'] = true,
    ['WEAPON_SPATULA'] = true,
    ['WEAPON_STEPLADDER'] = true,
    ['WEAPON_STREETLIGHT'] = true,
    ['WEAPON_TOASTER'] = true,
    ['WEAPON_VACUUM'] = true,
    ['WEAPON_WRONGWAYSIGN'] = true,
    ['WEAPON_YARI'] = true,
    ['WEAPON_BLACKBELT'] = true,
    ['WEAPON_BENTFORK'] = true,
    ['WEAPON_BLACKBACKPACK'] = true,
    ['WEAPON_BRCHICKEN'] = true,
    ['WEAPON_DOORBARS'] = true,
    ['WEAPON_EARBUDBLADE'] = true,
    ['WEAPON_HONEYDIPPER'] = true,
    ['WEAPON_KETTLE'] = true,
    ['WEAPON_LEATHERBRIEFCASE'] = true,
    ['WEAPON_MAKESHIFTKNIFE'] = true,
    ['WEAPON_MEASURINGCUP'] = true,
    ['WEAPON_MODDEDNIGHTSTICK'] = true,
    ['WEAPON_TRAYRACK'] = true,
    ['WEAPON_POKER'] = true,
    ['WEAPON_PRISONKEY'] = true,
    ['WEAPON_PRISTOI'] = true,
    ['WEAPON_REDBACKPACK'] = true,
    ['WEAPON_RULER'] = true,
    ['WEAPON_SHIV'] = true,
    ['WEAPON_SOLIDOOR'] = true,
    ['WEAPON_TEAPOT'] = true,
    ['WEAPON_VIOBACKPACK'] = true,
    ['WEAPON_PEELER'] = true,
    ['WEAPON_G36'] = true,
    ['WEAPON_G3_2'] = true,
    ['WEAPON_L85_CHR'] = true,
    ['lewall_alien'] = true,
    ['lewall_alien2'] = true,
    ['lewall_alien3'] = true,
    ['lewall_alien4'] = true,
    ['lewall_alien5'] = true,
    ['lewall_bulldog'] = true,
    ['lewall_cowboy'] = true,
    ['lewall_crab'] = true,
    ['lewall_cthulhu'] = true,
    ['lewall_dino'] = true,
    ['lewall_dog'] = true,
    ['lewall_dog2'] = true,
    ['lewall_doggy'] = true,
    ['lewall_dragon'] = true,
    ['lewall_dragon2'] = true,
    ['lewall_dragon3'] = true,
    ['lewall_parrot'] = true,
    ['lewall_rabbit'] = true,
    ['lewall_saw'] = true,
    ['lewall_shiba'] = true,
    ['lewall_snake'] = true,
    ['lewall_spider'] = true,
    ['lewall_tiger'] = true,
    ['lewall_witch'] = true,
    ['WEAPON_R90_CHR'] = true,
    ['WEAPON_VX_SCORPION_CHR'] = true,
    ['WEAPON_ASSAULTRIFLECUPID'] = true,
    ['WEAPON_ASSAULTRIFLE_MK2_DARKMATTER'] = true,
    ['WEAPON_CARBINERIFLE_MK2_DARKMATTER'] = true,
    ['WEAPON_SPECIALCARBINE_MK2_DARKMATTER'] = true,
    ['WEAPON_MICROSMG_DARKMATTER'] = true,
    ['WEAPON_REVOLVER_MK2_DARKMATTER'] = true,
    ['WEAPON_KNUCKLE_DARKMATTER'] = true,
    ['WEAPON_M249'] = true,
    ['WEAPON_MK14'] = true,
    ['WEAPON_RRT14_GANG'] = true,
    ['WEAPON_P320_GANG'] = true,
}

Continental.Rank = { --Faut trier du plus important au moins important
    'legendary',
    'platinium',
    'diamond',
    'gold'
}