-- Merged from foodsystem/config.lua. Do NOT reset Config here, es_extended owns it.

food = {
    {fooditem = "donut", give = 20, message = "~g~Vous avez mangé un donut", prop = "prop_amb_donut", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "poulsand", give = 60, message = "~g~Vous avez mangé un sandwich au poulet", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "thonsand", give = 50, message = "~g~Vous avez mangé un sandwich au thon", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "saumsand", give = 70, message = "~g~Vous avez mangé un sandwich saumon fromage frais", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "cafe", give = 20, message = "~g~Vous avez bu un café", prop = "p_amb_coffeecup_01", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "coca", give = 30, message = "~g~Vous avez bu un Coca Cola", prop = "prop_ecola_can", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "chips", give = 25, message = "~g~Vous avez mangé un paquet de chips", prop = "ng_proc_food_chips01b", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "chocolat", give = 20, message = "~g~Vous avez mangé une barre de chocolat", prop = "prop_choc_ego", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "rhum", give = 30, message = "~g~Vous avez bu un verre de rhum", prop = "prop_drink_whisky", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "champagne", give = 20, message = "~g~Vous avez bu un verre de champagne", prop = "prop_drink_champ", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "vine", give = 30, message = "~g~Vous avez bu un verre de vin", prop = "prop_drink_redwine", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "biere", give = 30, message = "~g~Vous avez bu une bière", prop = "prop_drink_redwine", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "vodka", give = 30, message = "~g~Vous avez bu un verre de vodka", prop = "prop_drink_whtwine", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "whisky", give = 30, message = "~g~Vous avez bu un verre de whisky", prop = "prop_drink_whisky", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "bieredequalite", give = 35, message = "~g~Vous avez bu une bière de qualité", prop = "prop_beer_blr", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "gin", give = 30, message = "~g~Vous avez bu un verre de gin", prop = "prop_drink_whtwine", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "eau", give = 40, message = "~g~Vous avez bu une bouteille d'eau", prop = "prop_ld_flow_bottle", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "bolfruit", give = 10, message = "~g~Vous avez mangé un bol de fruits", prop = "prop_fruit_basket", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "cacahuetes", give = 10, message = "~g~Vous avez mangé des cacahuètes", prop = "prop_fruit_basket", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "hotdog", give = 70, message = "~g~Vous avez mangé des hotdogs", prop = "prop_cs_hotdog_02", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "popcorn", give = 15, message = "~g~Vous avez mangé du popcorn", prop = "sempre_delperropier_popcorn_box", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "cotton", give = 10, message = "~g~Vous avez mangé de la barbe a papa", prop = "sempre_delperropier_candycotton_prop", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "burger", give = 20, message = "~g~Vous avez mangé des mini-burgers", prop = "prop_cs_burger_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "glace", give = 50, message = "~g~Vous avez mangé une glace", prop = "p_amb_coffeecup_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "nouilles", give = 50, message = "~g~Vous avez mangé des nouilles", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "icetea", give = 30, message = "~g~Vous avez bu un ice tea", prop = "prop_ecola_can", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "milkshake", give = 50, message = "~g~Vous avez bu un milkshake", prop = "prop_ecola_can", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "batonnet", give = 75, message = "~g~Vous avez mangé un batonnet de fromage", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "frites", give = 75, message = "~g~Vous avez mangé des frites", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "sandsteak", give = 75, message = "~g~Vous avez mangé un Sandwich Steak et fromage", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "the", give = 30, message = "~g~Vous avez bu un thé", prop = "prop_drink_whisky", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "sake", give = 30, message = "~g~Vous avez bu un saké", prop = "prop_drink_redwine", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "cocktail", give = 25, message = "~g~Vous avez bu un cocktail", prop = "prop_drink_redwine", isfood = 0, isdrink = 0, isdrunk = 1},
    {fooditem = "caprisun", give = 30, message = "~g~Vous avez bu un caprinsun", prop = "prop_ecola_can", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "bluebull", give = 40, message = "~g~Vous avez bu un Blue bull", prop = "prop_energy_drink", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "ayran", give = 30, message = "~g~Vous avez bu un ayran", prop = "p_amb_coffeecup_01", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "saucisson", give = 75, message = "~g~Vous avez mangé un saucisson", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "lattefraise", give = 50, message = "~y~Vous avez bu un latté fraise", prop = "p_amb_coffeecup_01", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "bubbletea", give = 50, message = "~y~Vous avez bu un bubble tea", prop = "p_amb_coffeecup_01", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "lattematcha", give = 50, message = "~y~Vous avez bu un latté matcha", prop = "p_amb_coffeecup_01", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "limonadejaponaise", give = 40, message = "~y~Vous avez bu une limonade japonaise", prop = "p_amb_coffeecup_01", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "menusushi", give = 30, message = "~y~Vous avez mangé un menu sushi", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "menutempura", give = 40, message = "~y~Vous avez mangé un menu tempura", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "yakitori", give = 15, message = "~y~Vous avez mangé un yakitori", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "soupemiso", give = 20, message = "~y~Vous avez mangé une soupe miso", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "cakejaponais", give = 60, message = "~y~Vous avez mangé un cake japonais", prop = "cake_strawberry", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "croffle", give = 40, message = "~y~Vous avez mangé un croffle", prop = "swissroll", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "mochi", give = 35, message = "~y~Vous avez mangé un mochi", prop = "mochi_duck", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pancakes", give = 60, message = "~y~Vous avez mangé des pancakes", prop = "cake_chocolate", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "tangulu", give = 35, message = "~y~Vous avez mangé un tangulu", prop = "pop_purple", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "wrap", give = 40, message = "~y~Vous avez mangé un wrap", prop = "prop_cs_burger_01", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "sundae_caramel", give = 20, message = "~y~Vous avez mangé un sundae caramel", prop = "pop_darkpurple", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "sundae_chocolat", give = 20, message = "~y~Vous avez mangé un sundae chocolat", prop = "pop_chocolate", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "sundae_fraise", give = 20, message = "~y~Vous avez mangé un sundae fraise", prop = "pop_red", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "granita", give = 20, message = "~y~Vous avez mangé un granita", prop = "drink_lime", isfood = 0, isdrink = 1, isdrunk = 0},
    {fooditem = "jus_orange_petillant", give = 40, message = "~y~Vous avez bu un jus d'orange pétillant", prop = "prop_food_cb_juice02", isfood = 0, isdrink = 1, isdrunk = 0},
}

foodfull = {
    {fooditem = "menuburger", give = 40, message = "~g~Vous avez mangé un menu burger", prop = "prop_cs_burger_01", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "menuburgerxl", give = 70, message = "~g~Vous avez mangé un menu burger XL", prop = "prop_cs_burger_01", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "menuvege", give = 30, message = "~g~Vous avez mangé un menu burger végé", prop = "prop_cs_burger_01", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "menuenfant", give = 25, message = "~g~Vous avez mangé un menu enfant", prop = "prop_cs_burger_01", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "menuramen", give = 50, message = "~g~Vous avez mangé un menu ramen", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "menusushi", give = 30, message = "~g~Vous avez mangé un menu sushi", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "menutempura", give = 40, message = "~g~Vous avez mangé un menu tempura", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "yakitori", give = 15, message = "~g~Vous avez mangé un yakitori", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "soupemiso", give = 20, message = "~g~Vous avez mangé une soupe miso", prop = "ng_proc_food_aple2a", isfood = 1, isdrink = 1, isdrunk = 0},
    {fooditem = "kebab", give = 50, message = "~g~Vous avez mangé un kebab", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "biscuit", give = 30, message = "~g~Vous avez mangé un biscuit", prop = "prop_choc_ego", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "clubsand", give = 30, message = "~g~Vous avez mangé un club sandwich", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "frenchtacos", give = 50, message = "~g~Vous avez mangé un french tacos", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pizzamarguerita", give = 40, message = "~g~Vous avez mangé une pizza marguerita", prop = "knjgh_pizzaslice4", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pizzamexicaine", give = 65, message = "~g~Vous avez mangé une pizza mexicaine", prop = "knjgh_pizzaslice3", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pizzaorientale", give = 65, message = "~g~Vous avez mangé une pizza orientale", prop = "knjgh_pizzaslice2", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pizzapepperoni", give = 60, message = "~g~Vous avez mangé une pizza pepperoni", prop = "knjgh_pizzaslice5", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pizzavegetarienne", give = 50, message = "~g~Vous avez mangé une pizza végétarienne", prop = "knjgh_pizzaslice2", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "burgerfrites", give = 75, message = "~g~Vous avez mangé un Burger frites", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "fritesbacon", give = 75, message = "~g~Vous avez mangé des Frites bacon et fromage", prop = "prop_sandwich_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "sandkebab", give = 40, message = "~g~Vous avez mangé un sandwich kebab", prop = "prop_cs_burger_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "assiettekebab", give = 60, message = "~g~Vous avez mangé une assiette kebab", prop = "prop_cs_burger_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "adana", give = 50, message = "~g~Vous avez mangé un kebab adana", prop = "prop_cs_burger_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "sandfalafel", give = 20, message = "~g~Vous avez mangé un sandwich falafel", prop = "prop_cs_burger_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pide", give = 35, message = "~g~Vous avez mangé un pidé", prop = "prop_cs_burger_01", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "cakejaponais", give = 60, message = "~y~Vous avez mangé un cake japonais", prop = "cake_strawberry", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "croffle", give = 40, message = "~y~Vous avez mangé un croffle", prop = "swissroll", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "mochi", give = 35, message = "~y~Vous avez mangé un mochi", prop = "mochi_duck", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "pancakes", give = 60, message = "~y~Vous avez mangé des pancakes", prop = "cake_chocolate", isfood = 1, isdrink = 0, isdrunk = 0},
    {fooditem = "tangulu", give = 35, message = "~y~Vous avez mangé un tangulu", prop = "pop_purple", isfood = 1, isdrink = 0, isdrunk = 0}
}
